config/routes.rb
# frozen_string_literal: true

# This file is a part of Projman, a group project orchestrator and management system,
# made by Team 5 for the COM3420 module [Software Hut] at the University of Sheffield.

Rails.application.routes.draw do
  devise_for :users

  mount EpiCas::Engine, at: "/"

  root "course_project#index"

  get "/profile", to: "page#profile"
  post "/profile/request-title-change", to: "page#request_title_change"
  
  get "/privacy", to: "page#privacy"
  get "/accessibility", to: "page#accessibility"

  get "/mail", to: "mailing#mail"
  post "/mail", to: "mailing#create"

  resources :projects, controller: :course_project do
    resource :milestone_responses, only: [:create], controller: :milestone_response

    post "/new", to: "course_project#create", on: :collection
    post "/edit", to: "course_project#update", on: :member
    post "/delete", to: "course_project#delete", on: :member

    # AJAX
    post "add_project_choice", on: :collection
    post "remove_project_choice", on: :collection
    post "add_project_milestone", on: :collection
    post "remove_project_milestone", on: :collection
    post "add_to_facilitator_selection", on: :collection
    post "remove_from_facilitator_selection", on: :collection
    post "add_facilitator_selection", on: :collection
    post "remove_facilitator", on: :collection
    post "clear_facilitator_selection", on: :collection
    post "toggle_project_choices", on: :collection
    get "search_facilitators", on: :collection
    get "get_milestone_data", on: :collection
    get "remove_milestone_email", on: :collection
    post "set_milestone_email_data", on: :collection
    post "set_milestone_comment", on: :collection
    get "search_facilitators_student", on: :collection
    get "search_facilitators_staff", on: :collection
    get "search_student_name", on: :collection

    post ":group_id/send-chat-message", to: "course_project#send_chat_message", on: :collection

    post "remake_teams", on: :member

    resources :teams, controller: :group do
      get "/teams", to: "group#index", on: :member
      post "facilitator_emails", on: :member
      post "set_facilitator", on: :member
      post "current_subproject", on: :member
      post "set_subproject", on: :member
      get "search_module_students", on: :collection
      post "add_student_to_team", on: :member
      post "remove_students_from_team", on: :member
    end

    resources :progress_form, controller: :progress_form do
      post "add_question" => "progress_form#add_question", on: :collection
      post "add_question" => "progress_form#add_question", on: :member
      post "delete_question" => "progress_form#delete_question", on: :collection
      post "delete_question" => "progress_form#delete_question", on: :member
      post "save_form" => "progress_form#save_form", on: :collection
      post "save_form" => "progress_form#save_form", on: :member
      post "delete_form" => "progress_form#delete_form", on: :collection
      post "delete_form" => "progress_form#delete_form", on: :member
      post "change_title" => "progress_form#change_title", on: :member
      post "change_title" => "progress_form#change_title", on: :collection

      post "show_new" => "progress_form#show_new", on: :collection
    end

    resources :mark_scheme, controller: :mark_scheme do
      post "add_section" => "mark_scheme#add_section", on: :collection
      post "add_section" => "mark_scheme#add_section", on: :member
      post "delete_section" => "mark_scheme#delete_section", on: :collection
      post "delete_section" => "mark_scheme#delete_section", on: :member
      post "save" => "mark_scheme#save", on: :collection
      post "save" => "mark_scheme#save", on: :member

      post 'add_to_assessors_selection' => 'mark_scheme#add_to_assessors_selection', on: :collection
      post 'add_assessors_selection' => 'mark_scheme#add_assessors_selection', on: :collection
      post 'clear_assessors_selection' => 'mark_scheme#clear_assessors_selection', on: :collection
      post 'remove_from_assessor_selection' => 'mark_scheme#remove_from_assessor_selection', on: :collection
      post 'remove_assessor_from_section' => 'mark_scheme#remove_assessor_from_section', on: :collection
      post 'get_assignable_teams' => 'mark_scheme#get_assignable_teams', on: :collection
      post 'assign_teams' => 'mark_scheme#assign_teams', on: :collection
      post 'auto_assign_teams' => 'mark_scheme#auto_assign_teams', on: :collection
      get 'search_assessors' => 'mark_scheme#search_assessors', on: :collection
      post "export_mark_scheme_with_results" => "mark_scheme#export_mark_scheme_with_results", on: :collection
      post "import_mark_scheme" => "mark_scheme#import_mark_scheme", on: :collection

      get 'marks' => 'mark_scheme#marks', on: :collection
      post 'show_new', on: :collection
    end
  end

  resources :students, only: [:index], controller: :student do
    post "/update_selection" => "student#update_selection", on: :collection
    get "/search_students" => "student#search_students", on: :collection
    post "/confirm_selection" => "student#confirm_selection", on: :collection
    post "/clear_selection" => "student#clear_selection", on: :collection
    post "/clear_student" => "student#clear_student", on: :collection
    post "/remove_students_from_module" => "student#remove_students_from_module", on: :collection
  end

  resources :issues, only: %i[index create], controller: :issue do
    # AJAX
    post "update-selection", to: "issue#update_selection", on: :collection
    post "issue-response", to: "issue#issue_response", on: :collection
    post "update-status", to: "issue#update_status", on: :collection
  end

  resources :facilitators, only: [:index], controller: :facilitator do
    get "teams/:team_id", to: "facilitator#team", as: "facilitator_team", on: :collection
    get "teams/:team_id/progress_form/:milestone_id", to: "facilitator#progress_form", as: "progress_form",
                                                      on: :collection

    # AJAX
    post 'update_teams_list' => 'facilitator#update_teams_list', on: :collection
    post 'update_progress_form_response' => 'facilitator#update_progress_form_response', on: :collection
  end

  resources :markings, controller: :marking do
    post 'save' => 'marking#save', on: :collection
  end

  resources :modules, controller: :course_module do
    post "/delete", to: "course_module#delete", on: :member
  end
end

app/controllers/progress_form_controller.rb
# frozen_string_literal: true

# This file is a part of Projman, a group project orchestrator and management system,
# made by Team 5 for the COM3420 module [Software Hut] at the University of Sheffield.

class ProgressFormController < ApplicationController
  skip_authorization_check

  # For each route we protect it by checking if the user has update rights
  # to the attached course project. If they do, they by extension have full permissions
  # to viewing its progress forms.
  # This has to be done as the "ProgressForm" is not its own Model

  def index
    session[:current_project_id] = params[:project_id].to_i
    @current_project = CourseProject.find(session[:current_project_id])

    authorize! :update, @current_project

    # Get each progress form
    @progress_forms = get_progress_forms_for_project.sort_by(&:deadline)

    # Auto select the one with the furthest release date
    @progress_form = @progress_forms.last
    session[:progress_form_id] = @progress_form.nil? ? -1 : @progress_form.id
  end

  def new
    session[:current_project_id] = params[:project_id].to_i
    @current_project = CourseProject.find(session[:current_project_id])

    authorize! :update, @current_project

    # Initialise new form
    # NOTE: Will not work without parse and to_json because its loaded from db as json
    #       so this just keeps it always as json.
    session[:new_progress_form] = JSON.parse({
      "questions":  [],
      "attendance": true
    }.to_json)

    session[:progress_form_deadline] = ""

    @progress_form_json = session[:new_progress_form]
    @progress_form_deadline = ""
  end

  def edit
    session[:current_project_id] = params[:project_id].to_i
    @current_project = CourseProject.find(session[:current_project_id])

    authorize! :update, @current_project

    progress_form = Milestone.find(params[:id])
    if progress_form.nil?
      flash.alert = "Could not find progress form to edit."

      redirect_to project_progress_form_index_path
      return
    end

    # Can't edit released forms
    if progress_form.deadline <= DateTime.current
      flash.alert = "Cannot edit a released form."
      redirect_to project_progress_form_index_path
      return
    end

    # Load progress form data to edit
    session[:new_progress_form] = progress_form.json_data
    session[:progress_form_deadline] = progress_form.deadline

    @progress_form_json = session[:new_progress_form]
    @progress_form_deadline = progress_form.deadline
  end

  # AJAX Routes
  def add_question
    session[:current_project_id] = params[:project_id].to_i
    @current_project = CourseProject.find(session[:current_project_id])
    authorize! :update, @current_project
    question = params[:question]

    session[:new_progress_form]["questions"] = [] if session[:new_progress_form]["questions"].nil?

    # Handle errors
    if session[:new_progress_form]["questions"].include?(question)
      @error = "Cannot have duplicate questions."

    elsif question.blank?
      @error = "Question cannot be empty."

    else
      session[:new_progress_form]["questions"] << params[:question]
    end

    @progress_form_json = session[:new_progress_form]
    @progress_form_deadline = session[:progress_form_deadline]

    return unless request.xhr?

    respond_to(&:js)
  end

  def delete_question
    session[:current_project_id] = params[:project_id].to_i
    @current_project = CourseProject.find(session[:current_project_id])
    authorize! :update, @current_project
    # This won't throw an error if the index is invalid and an invalid index would mean the question isn't there,
    # so we can just re-render the partial anyways.
    session[:new_progress_form]["questions"].delete_at(params[:question_index])

    render partial: "progress_form",
           locals:
                    {
                      progress_form:     JSON.parse(session[:new_progress_form].to_json),
                      release_date:      session[:progress_form_deadline],
                      progress_response: nil,
                      group:             "None",
                      facilitator:       false,
                      editing_form:      true # Force editable because release date might not be set yet
                    }
  end

  def change_title
    session[:current_project_id] = params[:project_id].to_i
    @current_project = CourseProject.find(session[:current_project_id])
    authorize! :update, @current_project
    title = params[:title]

    taken_titles = get_progress_forms_for_project.map { |pf| pf.json_data["title"] }

    if taken_titles.include?(title)
      @error = "There is already a progress form with this title."

    elsif title.blank?
      @error = "Title cannot be empty."
    end

    if @error.nil?
      session[:new_progress_form]["title"] = title

      @progress_form_json = session[:new_progress_form]
      @progress_form_deadline = session[:progress_form_deadline]

    end

    return unless request.xhr?

    respond_to(&:js)
  end

  def save_form
    session[:current_project_id] = params[:project_id].to_i
    @current_project = CourseProject.find(session[:current_project_id])
    authorize! :update, @current_project
    # To save the form there must be at least one question
    if session[:new_progress_form]["questions"].empty?
      return render json: {
        status:  "error",
        message: "no_questions"
      }
    end

    # Session progress form deadline won't be set if we are creating new
    creating_new = session[:progress_form_deadline].nil? || session[:progress_form_deadline] == ""

    # Try find a pre-existing form to update
    unless creating_new
      milestone = get_progress_forms_for_project.select do |m|
        m.deadline.strftime("%Y-%m-%dT%H:%M") == session[:progress_form_deadline].strftime("%Y-%m-%dT%H:%M")
      end.first
    end

    # Update progress form, must be after get milestone incase 'primary key' changes
    session[:new_progress_form]["attendance"] = params[:attendance]

    # HTML date formatted like this YYYY-MM-DDT17:25
    formatted_deadline = params[:release_date].tr("T", " ")

    # Create or update milestone to represent the form
    if milestone.nil?
      milestone = Milestone.new(
        json_data:         session[:new_progress_form],
        deadline:          formatted_deadline,
        milestone_type:    :team,
        course_project_id: session[:current_project_id]
      )
    else
      if creating_new
        return render json: {
          status:  "error",
          message: "Cannot save progress form with duplicate release date."
        }
      end

      # Can't update released forms
      if milestone.deadline <= DateTime.current
        return render json: {
          status:   "already_released",
          message:  "Cannot update a released progress form.",
          redirect: project_progress_form_index_path
        }
      end

      # Update milestone data
      milestone.json_data = session[:new_progress_form]
      milestone.deadline = formatted_deadline
    end

    # For determining what milestone is a progress form.
    milestone.json_data["name"] = "progress_form"

    # Handle save failure
    unless milestone.save
      return render json: {
        status:  "error",
        message: "Failed to save progress form."
      }
    end

    # Can't redirect_to from ajax so return path to redirect
    render json: {
      status:   "success",
      message:  "Saved form",
      redirect: project_progress_form_index_path
    }
  end

  def delete_form
    session[:current_project_id] = params[:project_id].to_i
    @current_project = CourseProject.find(session[:current_project_id])
    authorize! :update, @current_project
    # Try find and delete a record if editing
    if params[:id]
      milestone = get_progress_forms_for_project.select { |m| m.id == params[:id].to_i }.first

      # Can't delete released forms
      if milestone.deadline <= DateTime.current
        flash.alert = "Cannot delete a released form."
        redirect_to project_progress_form_index_path
        return
      end

      # If we don't find a milestone to delete, there is no error because its already 'deleted'
      milestone&.destroy
    end

    session[:new_progress_form] = {}

    redirect_to action: :index
  end

  def show_new
    session[:current_project_id] = params[:project_id].to_i
    @current_project = CourseProject.find(session[:current_project_id])
    authorize! :update, @current_project
    return if params[:release_date] == ""

    # Update the current displayed form
    formatted_release_date = DateTime.parse(params[:release_date].tr("T", " "))

    @progress_form = get_progress_forms_for_project.select do |m|
      date_to_string(m.deadline) == date_to_string(formatted_release_date)
    end.first

    session[:progress_form_id] = @progress_form.id

    # Handle group not being specified
    if params[:group_name] == "None"
      group = params[:group_name]
    else
      group = CourseProject.find(session[:current_project_id]).groups.find_by(name: params[:group_name])

      @progress_response = @progress_form.milestone_responses.select do |mr|
        mr.json_data["group_id"] == group.id
      end.first

    end

    # Return the html for the new progress form
    render partial: "progress_form", locals:
      {
        progress_form_id:  @progress_form.id,
        progress_form:     @progress_form.json_data,
        release_date:      @progress_form.deadline,
        progress_response: @progress_response.nil? ? nil : @progress_response.json_data,
        group:,
        facilitator:       false,
        editing_form:      false
      }
  end

  private
    def get_progress_forms_for_project
      # Helper for returning the correct milestones
      Milestone.select do |m|
        m.json_data["name"] == "progress_form" &&
          m.course_project_id == session[:current_project_id]
      end
    end

    def date_to_string(date)

app/views/progress_form/_attendance.html.haml
-# This file is a part of Projman, a group project orchestrator and management system,
-# made by Team 5 for the COM3420 module [Software Hut] at the University of Sheffield.

- unique_id = "attendance-card"

// Define a style to enable/disable inputs for facilitator/module lead
- responding_style = ("pointer-events: none;" if !facilitator);

.card.mb-2
  %a.card-header.d-flex.justify-content-between.align-items-center{
    "data-bs-toggle" => "collapse",
    href: "##{unique_id}",
    role: "button",
    "data-accordion-toggle" => "",
    "aria-expanded" => "true",
    "aria-controls" => unique_id}

    .fs-5= "Attendance"
    %i.bi.bi-caret-right-fill

  .collapse.show{id: unique_id}
    .card-body
      - if group != "None"
        - group.students.each_with_index do |student, i|
          - student_attendance = attendance.nil? ? [false, ""] : attendance.fetch(i, [false, ""])

          .form-check{style: responding_style}
            %input.form-check-input.absent-checkbox{
              type: "checkbox",
              id: "absentCheckbox-#{student.id}",
              checked: student_attendance[0]}

            %label.form-check-label{ for: "absentCheckbox-#{student.id}" }= "#{student.forename} #{student.surname}"

          %input{
            type: "text",
            id: "reasonTextInput-#{student.id}",
            placeholder: "Reason for absence",
            value: student_attendance[1],
            class: ("form-control mb-3 absent-reason-input" + (" d-none" if student_attendance[0]).to_s),
            style: responding_style }

      - else
        // No group given, so display default students as example data for module lead preview
        - for n in 1..3 do
          .form-check{style: responding_style}
            %input.form-check-input.absent-checkbox{ type: "checkbox", id: "absentCheckbox-#{n}", checked: false }
            %label.form-check-label{ for: "absentCheckbox-#{n}" }= "Student #{n}"

          %input.form-control.mb-3.absent-reason-input{
            type: "text",
            id: "reasonTextInput-#{n}",
            placeholder: "Reason for absence",
            style: responding_style }



  :javascript
    document.addEventListener('change', function(event) {
      if (event.target && event.target.matches(".absent-checkbox")) {
        var checkboxId = event.target.id.split("-")[1];
        var textInputContainer = document.getElementById(`reasonTextInput-${checkboxId}`);

        if (event.target.checked) {
          textInputContainer.classList.add("d-none");
          textInputContainer.classList.remove("d-inline");
        }
        else {
          textInputContainer.classList.remove("d-none");
          textInputContainer.classList.add("d-inline");
        }
      }
    });

app/views/progress_form/_progress_form.html.haml
-# This file is a part of Projman, a group project orchestrator and management system,
-# made by Team 5 for the COM3420 module [Software Hut] at the University of Sheffield.

// Display
- unless progress_response.nil?
  %h5.fs-5= "Last updated by: " + (progress_response["facilitator_repr"] || "")

  %hr.divider

// Only show edit button if not editing and not facilitator and not released
- unless editing_form || facilitator || DateTime.current >= release_date
  = link_to edit_project_progress_form_path(id: progress_form_id), class: 'btn btn-outline-primary' do
    %i.bi.bi-pencil
    Edit
  %hr.divider

// Display attendance if required
- if progress_form["attendance"] && !editing_form
  - attendance = progress_response.nil? ? nil : progress_response["attendance"]
  = render partial: "progress_form/attendance", locals: {group: group, attendance: attendance, facilitator: facilitator}


// Display questions and their responses
- question_responses = progress_response.nil? ? [] : progress_response["question_responses"]

- unless progress_form["questions"].nil?
  - progress_form["questions"].each_with_index do |question, i|
    - question_response = question_responses.fetch(i, "")
    = render partial: "progress_form/question", locals: {question: question, question_index: (i + 1).to_s, facilitator: facilitator, question_response: question_response, editing_form: editing_form}

:javascript
  document.addEventListener("DOMContentLoaded", function() {
    // Listen for all clicks as the questions are loaded dynamically
    document.addEventListener("click", function(e) {
      if (event.target.matches('.delete-question-button')) {
        var question_index = event.target.id.replace("delete-question-", "");

        // Ajax to delete question
        fetch("delete_question", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "X-CSRF-Token": document.head.querySelector("meta[name=csrf-token]")?.content
          },
          body: JSON.stringify({
            question_index: parseInt(question_index - 1)
          })
        })
        .then(response => response.text())
        .then(data => {
          document.getElementById("progress-form-partial-container").innerHTML = data;
        })
        .catch(error => console.error("Error when deleting progress form question:", error));
      }
    });
  });

app/views/progress_form/_progress_form_builder.html.haml
-# This file is a part of Projman, a group project orchestrator and management system,
-# made by Team 5 for the COM3420 module [Software Hut] at the University of Sheffield.

.fs-2.semi-bold= title

.fs-4.semi-bold Settings
.row.align-items-center
  .col
    .form-check.form-switch
      %input.form-check-input{ type: "checkbox", id: "attendance-checkbox", checked: @progress_form_json["attendance"] }
      %label.form-check-label{ for: "attendance-checkbox" }= "Require attendance?"

  .col-auto
    %label{for: "release-date-input"} Release Date
    - html_formatted_release_date = ""
    - unless @progress_form_deadline.nil? || @progress_form_deadline == ""
      - html_formatted_release_date = @progress_form_deadline.strftime("%Y-%m-%dT%H:%M")

    %input.form-control#release-date-input{type: "datetime-local", value: html_formatted_release_date}
    %small.text-danger.d-none#release-date-input-error Must set a release date

%hr.divider

#progress-form-partial-container
  = render partial: "progress_form", locals: {progress_form: @progress_form_json, release_date: @progress_form_deadline, progress_response: nil, group: "None", facilitator: false, editing_form: true}

.modal.fade{ id: "add-question-modal", tabindex: "-1", "aria-labelledby": "add-question-modal", "aria-hidden": "true", "data-disallow-confirm-empty-input": "" }
  .modal-dialog.modal-dialog-centered.modal-dialog-scrollable
    .modal-content
      .modal-header
        %h1.modal-title.fs-5= "Add new question"
        %button.btn-close#add-question-close-button{ "aria-label": "Close", "data-bs-dismiss": "modal", type: "button" }

      = form_with(url: "add_question", method: :post, local: false, id: "add-question-form") do |form|
        .modal-body
          .form-group
            = form.text_area :question, class: "form-control", required: true, placeholder: "What is the weather like today?", id: "question-text-area"
            %small.text-danger.d-none#question-text-area-error Question cannot be empty

        .modal-footer
          = form.submit "Add", class: "btn btn-primary", id: "add-question-button"

%button.btn.btn-outline-primary.w-100{type: "button", id: "create-question-button", "data-bs-toggle": "modal", "data-bs-target": "#add-question-modal"}
  %i.bi.bi-plus-circle-fill
  Add new question

%small.text-danger.d-none#questions-error Must add a question

.d-flex.pb-3
  %div
    %button.btn.btn-success.mt-2#save-button{type: "button"}
      %i.bi.bi-floppy
      Save

  %div.ms-1
    = form_with(url: "delete_form", method: :post, local: true, id: "delete-form") do |form|
      = button_tag type: "submit", class: "btn btn-danger mt-2", id: "delete-button" do
        %i.bi.bi-trash
        Delete

:javascript
  // Helpers
  function dateToYYYYMMDDHHMM(date) {
    // Helper for parsing a date object to be used for min
    const year = date.getFullYear();
    const month = (date.getMonth() + 1).toString().padStart(2, "0");
    const day = date.getDate().toString().padStart(2, "0");
    const hours = date.getHours().toString().padStart(2, "0");
    const minutes = date.getMinutes().toString().padStart(2, "0");

    return `${year}-${month}-${day}T${hours}:${minutes}`;
  }

  document.addEventListener("DOMContentLoaded", function() {
    // Only display today and future times for the release date
    var minReleaseDate = new Date();
    minReleaseDate.setDate(minReleaseDate.getDate());

    // Set min attribute of date input to current date
    const releaseDateInput = document.getElementById("release-date-input");
    releaseDateInput.min = dateToYYYYMMDDHHMM(minReleaseDate);

    // Save form events
    const saveBtn = document.getElementById("save-button");
    const createQuestionButton = document.getElementById("create-question-button");
    const questionsError = document.getElementById("questions-error");
    saveBtn.addEventListener("click", function(e) {
      // Show any basic data validation errors
      let dataInvalid = false;

      let releaseDateInputError = document.getElementById("release-date-input-error");

      if (releaseDateInput.value === "") {
        // Show that it cannot be empty
        releaseDateInput.classList.add("is-invalid");
        releaseDateInputError.classList.remove("d-none");
        return;
      }
      else {
        releaseDateInput.classList.remove("is-invalid");
        releaseDateInputError.classList.add("d-none");
      }

      fetch("save_form", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "X-CSRF-Token": document.head.querySelector("meta[name=csrf-token]")?.content
        },
        body: JSON.stringify({
          "release_date": releaseDateInput.value,
          "attendance": document.getElementById("attendance-checkbox").checked
        })
      })
      .then(response => response.json())
      .then(json => {
        if (json["status"] === "success") {
          window.location.href = json["redirect"];
        }
        else {
          if (json["message"] === "no_questions") {
            createQuestionButton.classList.remove("btn-outline-primary");
            createQuestionButton.classList.add("btn-outline-danger");

            questionsError.classList.remove("d-none");
          }
          else {
            alert(json["message"]);
          }

          if (json["status"] === "already_released") {
            window.location.href = json["redirect"];
          }
        }
      })
      .catch(error => console.error("Error when trying to save form:", error));
    });

    document.getElementById("add-question-form").addEventListener("submit", function(e) {
      // When we submit the form, we add a question, so remove any no questions errors.
      questionsError.classList.add("d-none");

      createQuestionButton.classList.add("btn-outline-primary");
      createQuestionButton.classList.remove("btn-outline-danger");
    });
  });

app/views/progress_form/edit.html.haml
-# This file is a part of Projman, a group project orchestrator and management system,
-# made by Team 5 for the COM3420 module [Software Hut] at the University of Sheffield.

= render partial: 'course_project/components/project_info_header', locals: { project_id:  @current_project.id }

= render partial: "progress_form_builder", locals: {title: "Editing Progress Form"}

app/views/progress_form/index.html.haml
-# This file is a part of Projman, a group project orchestrator and management system,
-# made by Team 5 for the COM3420 module [Software Hut] at the University of Sheffield.

= render partial: 'course_project/components/project_info_header', locals: { project_id:  @current_project.id }

.row.align-items-center
  .col
    .fs-3.semi-bold Viewing Progress Forms

  .col-auto
    .dropdown.d-inline-block.flex-2
      %button.btn.btn-primary{
        type: "button",
        id: "release-date-selection-button",
        "data-bs-toggle": "dropdown",
        "aria-haspopup": "true",
        "aria-expanded": "false"}

        %span#release-date-selection-label= "Release Date: " + (@progress_form.nil? ? "" : @progress_form.deadline.strftime("%d/%m/%Y %H:%M"))

        %i.bi.bi-caret-down-fill

      .dropdown-menu{ "aria-labelledby": "release-date-selection-label" }
        - @progress_forms.each do |ms|
          - formatted_date = ms.deadline.strftime("%d/%m/%Y %H:%M")
          %a.dropdown-item{
            onclick: "updateReleaseDate('#{formatted_date}')" }= formatted_date

    .dropdown.d-inline-block
      %button.btn.btn-primary{
        type: "button",
        id: "team-selection-button",
        "data-bs-toggle": "dropdown",
        "aria-haspopup": "true",
        "aria-expanded": "false"}

        %span#team-selection-label Team: None
        %i.bi.bi-caret-down-fill

      .dropdown-menu{ "aria-labelledby": "team-selection-button", style: "max-height: 50vh; overflow-y: auto;" }
        %a.dropdown-item{ onclick: "updateTeam('None')" }= "None"

        %hr.dropdown-divider

        - @current_project.groups.each do |group|
          %a.dropdown-item{ onclick: "updateTeam('#{group.name}')" }= group.name

  .col-auto
    = link_to new_project_progress_form_path, class: 'btn btn-outline-primary' do
      %i.bi.bi-plus-circle-fill
      Create New

%hr.divider

- if @progress_form.nil?
  .d-flex.justify-content-center.pt-3
    %i.fs-5.fw-light No progress forms found for this project

- else
  #progress-form-partial-container
    = render partial: "progress_form", locals: {progress_form_id: @progress_form.id, progress_form: @progress_form.json_data, release_date: @progress_form.deadline, progress_response: nil, group: "None", facilitator: false, editing_form: false}

:javascript
  const releaseDateLabel = document.getElementById("release-date-selection-label");
  const teamLabel = document.getElementById("team-selection-label");

  function updateProgressForm() {
    // Make an ajax request to get a new form partial
    fetch("#{show_new_project_progress_form_index_path}", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-CSRF-Token": document.head.querySelector("meta[name=csrf-token]")?.content
      },
      body: JSON.stringify({
        release_date: releaseDateLabel.textContent.replace("Release Date: ", ""),
        group_name: teamLabel.textContent.replace("Team: ", "")
      })
    })
    .then(response => response.text())
    .then(data => {
      // Update partial container contents
      document.getElementById("progress-form-partial-container").innerHTML = data;

      // Set the release date
      document.getElementById("release-date-selection-label").textContent = releaseDateLabel.textContent;
    })
    .catch(error => console.error("Error when updating progress form partial:", error));
  }

  // Functions for updating dropdowns
  function updateReleaseDate(selection) {
    releaseDateLabel.textContent = "Release Date: " + selection;
    updateProgressForm();
  }

  function updateTeam(selection) {
    teamLabel.textContent = "Team: " + selection;
    updateProgressForm();
  }