config/routes.rb
# frozen_string_literal: true

# This file is a part of Projman, a group project orchestrator and management system,
# made by Team 5 for the COM3420 module [Software Hut] at the University of Sheffield.

Rails.application.routes.draw do
  devise_for :users

  mount EpiCas::Engine, at: "/"

  root "course_project#index"

  get "/profile", to: "page#profile"
  post "/profile/request-title-change", to: "page#request_title_change"
  
  get "/privacy", to: "page#privacy"
  get "/accessibility", to: "page#accessibility"

  get "/mail", to: "mailing#mail"
  post "/mail", to: "mailing#create"

  resources :projects, controller: :course_project do
    resource :milestone_responses, only: [:create], controller: :milestone_response

    post "/new", to: "course_project#create", on: :collection
    post "/edit", to: "course_project#update", on: :member
    post "/delete", to: "course_project#delete", on: :member

    # AJAX
    post "add_project_choice", on: :collection
    post "remove_project_choice", on: :collection
    post "add_project_milestone", on: :collection
    post "remove_project_milestone", on: :collection
    post "add_to_facilitator_selection", on: :collection
    post "remove_from_facilitator_selection", on: :collection
    post "add_facilitator_selection", on: :collection
    post "remove_facilitator", on: :collection
    post "clear_facilitator_selection", on: :collection
    post "toggle_project_choices", on: :collection
    get "search_facilitators", on: :collection
    get "get_milestone_data", on: :collection
    get "remove_milestone_email", on: :collection
    post "set_milestone_email_data", on: :collection
    post "set_milestone_comment", on: :collection
    get "search_facilitators_student", on: :collection
    get "search_facilitators_staff", on: :collection
    get "search_student_name", on: :collection

    post ":group_id/send-chat-message", to: "course_project#send_chat_message", on: :collection

    post "remake_teams", on: :member

    resources :teams, controller: :group do
      get "/teams", to: "group#index", on: :member
      post "facilitator_emails", on: :member
      post "set_facilitator", on: :member
      post "current_subproject", on: :member
      post "set_subproject", on: :member
      get "search_module_students", on: :collection
      post "add_student_to_team", on: :member
      post "remove_students_from_team", on: :member
    end

    resources :progress_form, controller: :progress_form do
      post "add_question" => "progress_form#add_question", on: :collection
      post "add_question" => "progress_form#add_question", on: :member
      post "delete_question" => "progress_form#delete_question", on: :collection
      post "delete_question" => "progress_form#delete_question", on: :member
      post "save_form" => "progress_form#save_form", on: :collection
      post "save_form" => "progress_form#save_form", on: :member
      post "delete_form" => "progress_form#delete_form", on: :collection
      post "delete_form" => "progress_form#delete_form", on: :member
      post "change_title" => "progress_form#change_title", on: :member
      post "change_title" => "progress_form#change_title", on: :collection

      post "show_new" => "progress_form#show_new", on: :collection
    end

    resources :mark_scheme, controller: :mark_scheme do
      post "add_section" => "mark_scheme#add_section", on: :collection
      post "add_section" => "mark_scheme#add_section", on: :member
      post "delete_section" => "mark_scheme#delete_section", on: :collection
      post "delete_section" => "mark_scheme#delete_section", on: :member
      post "save" => "mark_scheme#save", on: :collection
      post "save" => "mark_scheme#save", on: :member

      post 'add_to_assessors_selection' => 'mark_scheme#add_to_assessors_selection', on: :collection
      post 'add_assessors_selection' => 'mark_scheme#add_assessors_selection', on: :collection
      post 'clear_assessors_selection' => 'mark_scheme#clear_assessors_selection', on: :collection
      post 'remove_from_assessor_selection' => 'mark_scheme#remove_from_assessor_selection', on: :collection
      post 'remove_assessor_from_section' => 'mark_scheme#remove_assessor_from_section', on: :collection
      post 'get_assignable_teams' => 'mark_scheme#get_assignable_teams', on: :collection
      post 'assign_teams' => 'mark_scheme#assign_teams', on: :collection
      post 'auto_assign_teams' => 'mark_scheme#auto_assign_teams', on: :collection
      get 'search_assessors' => 'mark_scheme#search_assessors', on: :collection
      post "export_mark_scheme_with_results" => "mark_scheme#export_mark_scheme_with_results", on: :collection
      post "import_mark_scheme" => "mark_scheme#import_mark_scheme", on: :collection

      get 'marks' => 'mark_scheme#marks', on: :collection
      post 'show_new', on: :collection
    end
  end

  resources :students, only: [:index], controller: :student do
    post "/update_selection" => "student#update_selection", on: :collection
    get "/search_students" => "student#search_students", on: :collection
    post "/confirm_selection" => "student#confirm_selection", on: :collection
    post "/clear_selection" => "student#clear_selection", on: :collection
    post "/clear_student" => "student#clear_student", on: :collection
    post "/remove_students_from_module" => "student#remove_students_from_module", on: :collection
  end

  resources :issues, only: %i[index create], controller: :issue do
    # AJAX
    post "update-selection", to: "issue#update_selection", on: :collection
    post "issue-response", to: "issue#issue_response", on: :collection
    post "update-status", to: "issue#update_status", on: :collection
  end

  resources :facilitators, only: [:index], controller: :facilitator do
    get "teams/:team_id", to: "facilitator#team", as: "facilitator_team", on: :collection
    get "teams/:team_id/progress_form/:milestone_id", to: "facilitator#progress_form", as: "progress_form",
                                                      on: :collection

    # AJAX
    post 'update_teams_list' => 'facilitator#update_teams_list', on: :collection
    post 'update_progress_form_response' => 'facilitator#update_progress_form_response', on: :collection
  end

  resources :markings, controller: :marking do
    post 'save' => 'marking#save', on: :collection
  end

  resources :modules, controller: :course_module do
    post "/delete", to: "course_module#delete", on: :member
  end
end

app/controllers/mark_scheme_controller.rb
# frozen_string_literal: true

# This file is a part of Projman, a group project orchestrator and management system,
# made by Team 5 for the COM3420 module [Software Hut] at the University of Sheffield.

class MarkSchemeController < ApplicationController
  skip_authorization_check

  # For each route we protect it by checking if the user has update rights
  # to the attached course project. If they do, they by extension have full permissions
  # to its mark scheme.
  # This has to be done as the "MarkScheme" is not its own Model

  def index
    session[:current_project_id] = params[:project_id].to_i
    @current_project = CourseProject.find(session[:current_project_id])

    authorize! :update, @current_project

    milestone = get_mark_scheme
    return if milestone.nil?

    @mark_scheme = milestone.json_data
  end

  def new
    session[:current_project_id] = params[:project_id].to_i
    @current_project = CourseProject.find(session[:current_project_id])

    authorize! :update, @current_project

    mark_scheme = get_mark_scheme
    if mark_scheme.nil?
      session[:mark_scheme] = hash_to_json({
        "sections": []
      })
    else
      redirect_to edit_project_mark_scheme_path(id: mark_scheme.id)
    end
  end

  def edit
    session[:current_project_id] = params[:project_id].to_i
    @current_project = CourseProject.find(session[:current_project_id])

    authorize! :update, @current_project

    mark_scheme = get_mark_scheme
    if mark_scheme.nil?
      redirect_to new_project_mark_scheme_path
    else
      session[:mark_scheme] = mark_scheme.json_data
    end
  end

  def add_section
    session[:current_project_id] = params[:project_id].to_i
    @current_project = CourseProject.find(session[:current_project_id])
    authorize! :update, @current_project
    # Assessors would be a list of the assessor emails and then the marking is split evenly.
    section_title = params[:section_title]

    if session[:mark_scheme]["sections"].map { |s| s["title"] }.include?(section_title)
      @error = "Cannot have duplicate section titles."

    elsif section_title.blank?
      @error = "Section title cannot be empty."

    else
      section = { title: params[:section_title], description: "", max_marks: 0 }
      session[:mark_scheme]["sections"] << hash_to_json(section)
    end

    return unless request.xhr?

    respond_to(&:js)
  end

  def delete_section
    session[:current_project_id] = params[:project_id].to_i
    @current_project = CourseProject.find(session[:current_project_id])
    authorize! :update, @current_project
    # Find the section with the matching title and remove it
    target_index = -1
    session[:mark_scheme]["sections"].each_with_index do |section, i|
      if params["section_title"] == section["title"]
        target_index = i
        next
      end
    end

    return render json: { status: "error", message: "Failed to find matching section to remove." } if target_index == -1

    session[:mark_scheme]["sections"].delete_at(target_index)

    render json: { status: "success" }
  end

  def save
    session[:current_project_id] = params[:project_id].to_i
    @current_project = CourseProject.find(session[:current_project_id])
    authorize! :update, @current_project
    # Everything is taken from the inputs, the session is only used for rendering stuff.
    if params[:sections].empty?
      return render json: {
        status:  "error",
        message: "Must have at least one section!"
      }
    end

    # Ensure max marks are valid or return error
    params[:sections].each do |section|
      if !/\A\d+\z/.match?(section["max_marks"])
        return render json: {
          status:  "error",
          message: "Max marks must be a positive whole number."
        }
      end
    end

    milestone = get_mark_scheme

    # Update section data without resetting assigned assessors
    params[:sections].each_with_index do |section, i|
      session[:mark_scheme]["sections"][i]["title"] = section["title"]
      session[:mark_scheme]["sections"][i]["description"] = section["description"]
      session[:mark_scheme]["sections"][i]["max_marks"] = section["max_marks"]
    end

    # Create or update milestone to represent the form
    if milestone.nil?
      milestone = Milestone.new(
        json_data:         session[:mark_scheme],
        deadline:          Date.current.strftime("%Y-%m-%d"), # Deadline isn't used here
        milestone_type:    :team, # Marks will be given per team
        course_project_id: params[:project_id],
        system_type:       :marking_deadline
      )
    else
      milestone.json_data = session[:mark_scheme]
      milestone.deadline = Date.current.strftime("%Y-%m-%d") # Deadline isn't used here
    end

    # Handle save failure
    unless milestone.save
      return render json: {
        status:  "error",
        message: "Failed to save milestone when save mark scheme."
      }
    end

    # Can't redirect from ajax here, so must do it from js
    render json: {
      status:   "success",
      message:  "Saved mark scheme",
      redirect: project_mark_scheme_index_path
    }
  end

  def search_assessors
    session[:current_project_id] = params[:project_id].to_i
    @current_project = CourseProject.find(session[:current_project_id])
    authorize! :update, @current_project
    # Return all possible assessors for the current project, given the search criteria.
    query = params[:query]

    query = "" if query.nil?

    @results = Staff.select { |s| s.email.include?(query.downcase) }
    render json: @results.map(&:email)
  end

  def add_to_assessors_selection
    session[:current_project_id] = params[:project_id].to_i
    @current_project = CourseProject.find(session[:current_project_id])
    authorize! :update, @current_project
    # Section index is not a param in the confirm ajax, so set it here to use there.
    session[:current_section_index] = params[:section_index]

    # Handle invalid email by just not adding to selected
    return if Staff.where(email: params[:section_assessor_email]).first.nil?

    @assessor_email = params[:section_assessor_email]

    if @assessor_email.present?
      if session[:assessor_selection].nil?
        session[:assessor_selection] = [@assessor_email]
      elsif !(session[:assessor_selection].to_a.include?(@assessor_email))
        session[:assessor_selection] << @assessor_email
      else
        @assessor_email = nil
      end

    end

    if request.xhr?
      respond_to(&:js)
    else
      render :new
    end
  end

  def add_assessors_selection
    session[:current_project_id] = params[:project_id].to_i
    @current_project = CourseProject.find(session[:current_project_id])
    authorize! :update, @current_project
    section_index = session[:current_section_index].to_i

    milestone = get_mark_scheme
    mark_scheme = milestone.json_data

    # Initialise assessors if necessary
    mark_scheme["sections"][section_index]["assessors"] = {} if mark_scheme["sections"][section_index]["assessors"].nil?

    # Populate new assessor emails into mark scheme milestone json data
    session[:assessor_selection].each do |assessor|
      unless mark_scheme["sections"][section_index]["assessors"].include?(assessor)
        mark_scheme["sections"][section_index]["assessors"][assessor] = []
      end
    end

    # Update the mark scheme
    milestone.json_data = mark_scheme
    flash.alert = "Failed to assign assessors to mark scheme." unless milestone.save

    # Re-render the view for assessors
    @mark_scheme = milestone.json_data

    if request.xhr?
      respond_to(&:js)
    else
      render :new
    end
  end

  def remove_from_assessor_selection
    session[:current_project_id] = params[:project_id].to_i
    @current_project = CourseProject.find(session[:current_project_id])
    authorize! :update, @current_project
    @assessor_email = params[:item_text].strip
    session[:assessor_selection].delete(@assessor_email)
  end

  def clear_assessors_selection
    session[:current_project_id] = params[:project_id].to_i
    @current_project = CourseProject.find(session[:current_project_id])
    authorize! :update, @current_project
    # Reset assessor selection, only called when modal is first opened
    session[:assessor_selection] = []
  end

  def remove_assessor_from_section
    session[:current_project_id] = params[:project_id].to_i
    @current_project = CourseProject.find(session[:current_project_id])
    authorize! :update, @current_project
    mark_scheme = get_mark_scheme
    mark_scheme.json_data["sections"][params[:section_index]]["assessors"].delete(params[:email])

    flash.alert = "Failed to unassign assessor from section." unless mark_scheme.save

    render partial: "section_assessors", locals: { mark_scheme: mark_scheme.json_data }
  end

  def get_assignable_teams
    session[:current_project_id] = params[:project_id].to_i
    @current_project = CourseProject.find(session[:current_project_id])
    authorize! :update, @current_project
    # Return the remaining teams available to be assigned to a assessor for the given section
    # Also contains teams already assigned to the assessor

    groups = CourseProject.find(session[:current_project_id]).groups

    mark_scheme = get_mark_scheme

    section = mark_scheme.json_data["sections"][params[:section_index]]

    # Save params for submit modal
    session[:current_section_index] = params[:section_index]
    session[:current_assessor_email] = params[:email]

    groups_to_show = {}
    groups.each do |group|
      groups_to_show[group.name] = { id: group.id, already_assigned: false }
    end

    section["assessors"].each do |assessor, team_ids|
      team_ids.each do |team_id|
        team = Group.find(team_id)
        if assessor == params[:email]
          groups_to_show[team.name][:already_assigned] = true
        else
          groups_to_show.delete(team.name)
        end
      end
    end

app/views/mark_scheme/add_to_assessors_selection.js.haml
-# This file is a part of Projman, a group project orchestrator and management system,
-# made by Team 5 for the COM3420 module [Software Hut] at the University of Sheffield.

- if @assessor_email.present?
    var newPartialHTML = "#{j(render(partial: 'components/group-item-simple', locals: { item_text: @assessor_email, deletion_action_url: remove_from_assessor_selection_project_mark_scheme_index_path}))}";
    $("ul.list-group.list-group-flush", $(".modal.show")).append(newPartialHTML);
    
$("input.form-control.search-collection", $(".modal.show")).val('');

app/views/mark_scheme/index.html.haml
-# This file is a part of Projman, a group project orchestrator and management system,
-# made by Team 5 for the COM3420 module [Software Hut] at the University of Sheffield.

= render partial: 'course_project/components/project_info_header', locals: { project_id: @current_project.id }

.fs-3.semi-bold Mark Scheme

%div.mt-2
    %a.btn.btn-primary#new-mark-scheme-button{type: "button", href: new_project_mark_scheme_path}
        %i.bi.bi-box-arrow-up-right
        Create/Edit Marking Document

    %a.btn.btn-primary#view-marks-button{type: "button", href: marks_project_mark_scheme_index_path}
        %i.bi.bi-box-arrow-up-right
        View Marks For Teams

%div.mt-2
    %a.btn.btn-primary{
        type: "button",
        id: "import-mark-scheme-button",
        "data-bs-toggle": "modal",
        "data-bs-target": "#import-mark-scheme-modal"}
        %i.bi.bi-box-arrow-down
        Import Mark Scheme

    = link_to export_mark_scheme_with_results_project_mark_scheme_index_path, method: :post, id: 'export-button', class: "btn btn-primary #{@mark_scheme.nil? ? 'd-none' : ''}" do
        %i.bi.bi-box-arrow-up
        Export Marking as CSV

%hr.divider

.fs-4.semi-bold Assign assessors to sections

%hr.divider

#section-assessors
    = render partial: "section_assessors", locals: {mark_scheme: @mark_scheme}

// Add assessors modal
= render 'components/modal-search-multiple',
    modal_id: 'add-assessor-to-section-modal',
    autocomplete_method: search_assessors_project_mark_scheme_index_path,
    title: 'Add Assessor',
    prompt: "Input assessor's email",
    form_input_id: 'add-assessor-to-section-form',
    form_input_name: 'section_assessor_email',
    current_selection_text: 'current selection',
    list_group_id: 'assessor-selection-group-section',
    confirm_text: 'Confirm',
    confirm_onclick_function: "",
    add_to_selection_url: add_to_assessors_selection_project_mark_scheme_index_path,
    submission_url: add_assessors_selection_project_mark_scheme_index_path,
    on_open_action_url: clear_assessors_selection_project_mark_scheme_index_path,
    search_hidden_fields: {"section_index": -1}

// Assign teams to assessor model
.modal.fade{ id: "assign-teams-modal", tabindex: "-1", "aria-labelledby": "addassign-teams-modal", "aria-hidden": "true"}
    .modal-dialog.modal-dialog-centered.modal-dialog-scrollable
        .modal-content
            .modal-header
                %h1.modal-title.fs-5= "Assign teams to assessor"
                %button.btn-close#add-section-close-button{ "aria-label": "Close", "data-bs-dismiss": "modal", type: "button" }

            .modal-body
                .form-group#team-checkboxes-container
                    %h1.fs-6 Remaining teams
                    - CourseProject.find(params[:project_id]).groups.each do |group|
                        .form-check.form-switch.d-none.group-checkbox-container{
                            id: "group-checkbox-container-#{group.id}"}

                            %input.form-check-input.group-checkbox{
                                type: "checkbox", id: "group-checkbox-#{group.id}", checked: false }

                            %label.form-check-label{ for: "group-checkbox-#{group.id}" }= group.name

            .modal-footer.d-flex.justify-content-between
                .col-auto
                    %button.btn.btn-secondary{onclick: "toggleAllAssessors();"} Select all
                    %button.btn.btn-secondary{onclick: "toggleAllAssessors(false);"} Deselect all

                .col-auto.ml-auto
                    %button.btn.btn-primary{ type: "submit", id: "assign-teams-button", onclick: "assignTeams();"}= "Assign"

// Import mark scheme csv modal
.modal.fade{ id: "import-mark-scheme-modal", tabindex: "-1", "aria-labelledby": "addassign-teams-modal", 
             "aria-hidden": "true"}
    .modal-dialog.modal-dialog-centered.modal-dialog-scrollable
        .modal-content
            .modal-header
                %h1.modal-title.fs-5= "Import a Mark Scheme CSV"
                %button.btn-close#import-mark-scheme-close-button{ "aria-label": "Close", 
                                                            "data-bs-dismiss": "modal", type: "button" }

            = form_with url: import_mark_scheme_project_mark_scheme_index_path, multipart: true, local: false do |form|
                .modal-body
                    -# Custom styled file upload
                    %label.btn.btn-primary.me-3#upload-csv-button
                        %i.bi.bi-upload
                        Upload
                        
                        = file_field_tag :mark_scheme_csv, id: "mark-scheme-input", accept: '.csv', style: "display: none;", onchange: 'updateSelectedMarkSchemeCSV(this);'

                    %span#mark-scheme-csv-file-text
                        No file chosen

                    %i.bi.bi-trash#remove-file-button{type:"button", style:"display: none;", onclick:"removeSelectedMarkSchemeCSV()"}

                    %hr.divider

                    -# Display overwrite mark scheme warning
                    .alert.alert-warning.d-flex.justify-content-left.align-items-baseline
                        %i.bi.bi-exclamation-triangle-fill.me-2
                        %h5.fs-5 This will overwrite the existing mark scheme and any related marking!

                    .alert.alert-success.d-flex.justify-content-left.align-items-baseline
                        %i.bi.bi-info-circle.me-2
                        %h5.fs-5 The .csv file must be in the format: 'Section Title, Section Description, Max Marks'

                    -# Error display
                    .alert.alert-danger.d-flex.justify-content-left.align-items-baseline.d-none#import-error-container
                        %i.bi.bi-exclamation-diamond-fill.me-2
                        %h5.fs-5#import-error-message Error message
                        
                .modal-footer.d-flex.justify-content-between
                    .col-auto.ml-auto
                        = submit_tag "Import", class: "btn btn-primary"




:javascript
    function updateSectionIndex(i) {
        // Use hidden inputs to set the section_index on the controller
        $('.hidden-inputs-container').each(function(){
            var inputs = $(this).find('input');

            inputs.each(function() {
                if ($(this).attr("name") === "section_index") {
                    $(this).val(i);
                    return;
                }
            });
        });
    }

    function removeAssessor(section_index, email) {
        fetch("#{remove_assessor_from_section_project_mark_scheme_index_path}", {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "X-CSRF-Token": document.head.querySelector("meta[name=csrf-token]")?.content
                },
            body: JSON.stringify({
                section_index: section_index,
                email: email
            })
        })
        .then(response => response.text())
        .then(html => {
            $("#section-assessors").html(html.trim());
        })
        .catch(error => console.error("Error when trying to save remove assessor:", error));
    }

    function populateAssignTeams(section_index, email) {
        fetch("#{get_assignable_teams_project_mark_scheme_index_path}", {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "X-CSRF-Token": document.head.querySelector("meta[name=csrf-token]")?.content
                },
            body: JSON.stringify({
                section_index: section_index,
                email: email
            })
        })
        .then(response => response.json())
        .then(data => {
            // Reset state of all checkboxes groups to hidden
            document.querySelectorAll(".group-checkbox-container").forEach(function(element) {
                element.classList.add("d-none");
            });

            // Reset state of all checkboxes to off
            document.querySelectorAll(".group-checkbox").forEach(function(element) {
                element.checked = false;
            });

            // Display returned groups
            data.groups_to_show.forEach(function(group) {
                document.getElementById(`group-checkbox-container-${group.id}`).classList.remove("d-none");
                document.getElementById(`group-checkbox-${group.id}`).checked = group.already_assigned;
            });
        })
        .catch(error => console.error("Error when trying to assign teams to assessor:", error));
    }

    function toggleAllAssessors(on = true) {
        document.querySelectorAll(".group-checkbox").forEach(function(element) {
            // Get all the displayed checkboxes
            const id = element.id.replace("group-checkbox-", "");
            if (!document.getElementById(`group-checkbox-container-${id}`).classList.contains("d-none")) {
                element.checked = on;
            }
        });
    }

    function assignTeams() {
        // Find all the displayed checkboxes that are checked
        team_ids = []
        document.querySelectorAll(".group-checkbox").forEach(function(element) {
            if (element.checked) {
                const id = element.id.replace("group-checkbox-", "");

                if (!document.getElementById(`group-checkbox-container-${id}`).classList.contains("d-none")) {
                    team_ids.push(parseInt(id));
                }
            }
        });

        fetch("#{assign_teams_project_mark_scheme_index_path}", {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "X-CSRF-Token": document.head.querySelector("meta[name=csrf-token]")?.content
                },
            body: JSON.stringify({
                team_ids: team_ids
            })
        })
        .then(response => response.text())
        .then(html => {
            // Reset state of all checkboxes to hidden
            document.querySelectorAll(".group-checkbox-container").forEach(function(element) {
                element.classList.add("d-none");
            });

            // Hide modal and update html
            $("#assign-teams-modal").modal("hide");
            $("#section-assessors").html(html.trim());
        })
        .catch(error => console.error("Error when trying to assign teams to assessor:", error));
    }

    function autoAssignSection(section_index) {
        updateSectionIndex(section_index);

        fetch("#{auto_assign_teams_project_mark_scheme_index_path}", {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "X-CSRF-Token": document.head.querySelector("meta[name=csrf-token]")?.content
                },
            body: JSON.stringify({
                section_index: section_index
            })
        })
        .then(response => response.text())
        .then(html => {
            // Hide modal and update html
            $("#assign-teams-modal").modal("hide");
            $("#section-assessors").html(html.trim());
        })
        .catch(error => console.error("Error when trying to auto assign teams to assessor:", error));
    }

    function updateSelectedMarkSchemeCSV(input) {
        // This allows for the file input button to be styled, trade-off is setting the selected file name manually. 
        var fileName = input.files[0]?.name;

        if (!fileName) {
            return;
        }

        if (fileName.endsWith(".csv")) {
            document.getElementById("mark-scheme-csv-file-text").innerText = fileName;
           document.getElementById("remove-file-button").style.display = 'inline-block';
        }
    }

    function removeSelectedMarkSchemeCSV() {
        // Remove the currently selected csv
        document.getElementById("mark-scheme-input").value = null;
        document.getElementById("mark-scheme-csv-file-text").innerText = "No file chosen";
        document.getElementById("remove-file-button").style.display = "none";
    } 

app/views/mark_scheme/marks.html.haml
-# This file is a part of Projman, a group project orchestrator and management system,
-# made by Team 5 for the COM3420 module [Software Hut] at the University of Sheffield.

= render partial: 'course_project/components/project_info_header', locals: { project_id:  @current_project.id }

.row.align-items-center
    .col
        .fs-3.semi-bold Viewing Marks

    .col-auto
        .dropdown.d-inline-block
            %button.btn.btn-primary{
                type: "button",
                id: "team-selection-button",
                "data-bs-toggle": "dropdown",
                "aria-haspopup": "true",
                "aria-expanded": "false"}

                %span#team-selection-label Team: None
                %i.bi.bi-caret-down-fill

            .dropdown-menu{ "aria-labelledby": "team-selection-button", style: "max-height: 50vh; overflow-y: auto;" }
                %a.dropdown-item{ onclick: "updateTeam('None')" }= "None"

                %hr.dropdown-divider

                - @current_project.groups.each do |group|
                    %a.dropdown-item{ onclick: "updateTeam('#{group.name}')" }= group.name

%hr.divider

- if @mark_scheme.nil?
    .d-flex.justify-content-center.pt-3
        %i.fs-5.fw-light  No mark scheme for this project.

- else
    #marking-table-partial-container
        = render partial: "marking_table", locals: {}

:javascript
    const teamLabel = document.getElementById("team-selection-label");

    function updateMarkingTable() {
        // Make an ajax request to get a new form partial
        fetch("#{show_new_project_mark_scheme_index_path}", {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "X-CSRF-Token": document.head.querySelector("meta[name=csrf-token]")?.content
            },
            body: JSON.stringify({
                group_name: teamLabel.textContent.replace("Team: ", "")
            })
        })
        .then(response => response.text())
        .then(data => {
            // Update partial container contents
            document.getElementById("marking-table-partial-container").innerHTML = data;
        })
        .catch(error => console.error("Error when updating marking table partial:", error));
    }

    function updateTeam(selection) {
        teamLabel.textContent = "Team: " + selection;
        updateMarkingTable();
    }