config/routes.rb
# frozen_string_literal: true

# This file is a part of Projman, a group project orchestrator and management system,
# made by Team 5 for the COM3420 module [Software Hut] at the University of Sheffield.

Rails.application.routes.draw do
  devise_for :users

  mount EpiCas::Engine, at: "/"

  root "course_project#index"

  get "/profile", to: "page#profile"
  post "/profile/request-title-change", to: "page#request_title_change"
  
  get "/privacy", to: "page#privacy"
  get "/accessibility", to: "page#accessibility"

  get "/mail", to: "mailing#mail"
  post "/mail", to: "mailing#create"

  resources :projects, controller: :course_project do
    resource :milestone_responses, only: [:create], controller: :milestone_response

    post "/new", to: "course_project#create", on: :collection
    post "/edit", to: "course_project#update", on: :member
    post "/delete", to: "course_project#delete", on: :member

    # AJAX
    post "add_project_choice", on: :collection
    post "remove_project_choice", on: :collection
    post "add_project_milestone", on: :collection
    post "remove_project_milestone", on: :collection
    post "add_to_facilitator_selection", on: :collection
    post "remove_from_facilitator_selection", on: :collection
    post "add_facilitator_selection", on: :collection
    post "remove_facilitator", on: :collection
    post "clear_facilitator_selection", on: :collection
    post "toggle_project_choices", on: :collection
    get "search_facilitators", on: :collection
    get "get_milestone_data", on: :collection
    get "remove_milestone_email", on: :collection
    post "set_milestone_email_data", on: :collection
    post "set_milestone_comment", on: :collection
    get "search_facilitators_student", on: :collection
    get "search_facilitators_staff", on: :collection
    get "search_student_name", on: :collection

    post ":group_id/send-chat-message", to: "course_project#send_chat_message", on: :collection

    post "remake_teams", on: :member

    resources :teams, controller: :group do
      get "/teams", to: "group#index", on: :member
      post "facilitator_emails", on: :member
      post "set_facilitator", on: :member
      post "current_subproject", on: :member
      post "set_subproject", on: :member
      get "search_module_students", on: :collection
      post "add_student_to_team", on: :member
      post "remove_students_from_team", on: :member
    end

    resources :progress_form, controller: :progress_form do
      post "add_question" => "progress_form#add_question", on: :collection
      post "add_question" => "progress_form#add_question", on: :member
      post "delete_question" => "progress_form#delete_question", on: :collection
      post "delete_question" => "progress_form#delete_question", on: :member
      post "save_form" => "progress_form#save_form", on: :collection
      post "save_form" => "progress_form#save_form", on: :member
      post "delete_form" => "progress_form#delete_form", on: :collection
      post "delete_form" => "progress_form#delete_form", on: :member
      post "change_title" => "progress_form#change_title", on: :member
      post "change_title" => "progress_form#change_title", on: :collection

      post "show_new" => "progress_form#show_new", on: :collection
    end

    resources :mark_scheme, controller: :mark_scheme do
      post "add_section" => "mark_scheme#add_section", on: :collection
      post "add_section" => "mark_scheme#add_section", on: :member
      post "delete_section" => "mark_scheme#delete_section", on: :collection
      post "delete_section" => "mark_scheme#delete_section", on: :member
      post "save" => "mark_scheme#save", on: :collection
      post "save" => "mark_scheme#save", on: :member

      post 'add_to_assessors_selection' => 'mark_scheme#add_to_assessors_selection', on: :collection
      post 'add_assessors_selection' => 'mark_scheme#add_assessors_selection', on: :collection
      post 'clear_assessors_selection' => 'mark_scheme#clear_assessors_selection', on: :collection
      post 'remove_from_assessor_selection' => 'mark_scheme#remove_from_assessor_selection', on: :collection
      post 'remove_assessor_from_section' => 'mark_scheme#remove_assessor_from_section', on: :collection
      post 'get_assignable_teams' => 'mark_scheme#get_assignable_teams', on: :collection
      post 'assign_teams' => 'mark_scheme#assign_teams', on: :collection
      post 'auto_assign_teams' => 'mark_scheme#auto_assign_teams', on: :collection
      get 'search_assessors' => 'mark_scheme#search_assessors', on: :collection
      post "export_mark_scheme_with_results" => "mark_scheme#export_mark_scheme_with_results", on: :collection
      post "import_mark_scheme" => "mark_scheme#import_mark_scheme", on: :collection

      get 'marks' => 'mark_scheme#marks', on: :collection
      post 'show_new', on: :collection
    end
  end

  resources :students, only: [:index], controller: :student do
    post "/update_selection" => "student#update_selection", on: :collection
    get "/search_students" => "student#search_students", on: :collection
    post "/confirm_selection" => "student#confirm_selection", on: :collection
    post "/clear_selection" => "student#clear_selection", on: :collection
    post "/clear_student" => "student#clear_student", on: :collection
    post "/remove_students_from_module" => "student#remove_students_from_module", on: :collection
  end

  resources :issues, only: %i[index create], controller: :issue do
    # AJAX
    post "update-selection", to: "issue#update_selection", on: :collection
    post "issue-response", to: "issue#issue_response", on: :collection
    post "update-status", to: "issue#update_status", on: :collection
  end

  resources :facilitators, only: [:index], controller: :facilitator do
    get "teams/:team_id", to: "facilitator#team", as: "facilitator_team", on: :collection
    get "teams/:team_id/progress_form/:milestone_id", to: "facilitator#progress_form", as: "progress_form",
                                                      on: :collection

    # AJAX
    post 'update_teams_list' => 'facilitator#update_teams_list', on: :collection
    post 'update_progress_form_response' => 'facilitator#update_progress_form_response', on: :collection
  end

  resources :markings, controller: :marking do
    post 'save' => 'marking#save', on: :collection
  end

  resources :modules, controller: :course_module do
    post "/delete", to: "course_module#delete", on: :member
  end
end

app/controllers/issue_controller.rb
# frozen_string_literal: true

# This file is a part of Projman, a group project orchestrator and management system,
# made by Team 5 for the COM3420 module [Software Hut] at the University of Sheffield.

# Controller for managing issue-related actions such as:
#   - Creating an issue
#   - Updating the selction of issues being shown
#   - Handling response to issues
#   - Updating the status of an issue
class IssueController < ApplicationController
  authorize_resource class: false

  def index
    @selected_project = if params[:selected_project].nil?
      "All"
    else
      params[:selected_project]
    end

    @selected_order = if params[:selected_order].nil?
      "Created At"
    else
      params[:selected_order]
    end

    get_issues

    render "index"
  end

  # Updates the current selection of issues.
  # @return [JavaScript Response] A javascript response which rerenders the
  #   page with the updated collection of issues in specified order.
  def update_selection
    @selected_project = params[:selected_project]
    @selected_order = params[:selected_order]

    get_issues(@selected_project, @selected_order)

    return unless request.xhr?

    respond_to(&:js)
  end

  # Creates a new issue.
  # @return [JavaScript Response] A javascript response which closes the modal
  #   and shows a success message if successful.
  def create
    json_data = {
      title:       params[:title],
      content:     params[:description],
      author:      params[:author],
      reopened_by: "",
      updated:     false
    }

    current_project_id = params[:project_id]
    group = current_user.student.groups.find_by(course_project_id: current_project_id)

    @issue = Event.new(completed: false, event_type: :issue, json_data:, group_id: group.id,
                       student_id: current_user.student.id)

    return unless @issue.save
    return unless request.xhr?

    respond_to(&:js)
  end

  # Handles the creation of an EventResponse to an issue.
  # @return [JavaScript Response] A javascript response which rerenders the
  #   issue box to upadate with new issue response and checks notification logic
  #   to see if notification icon needs to be removed.
  def issue_response
    @issue = Event.find(params[:issue_id])

    @selected_project = params[:selected_project]
    @selected_order = params[:selected_order]

    json_data = {
      content:   params[:response],
      author:    params[:author],
      timestamp: Time.zone.now
    }

    if current_user.is_staff?
      @issue_response = EventResponse.new(json_data:, event_id: params[:issue_id],
                                          staff_id: current_user.staff.id)

      @issue.json_data["reopened_by"] = "" if @issue.json_data["reopened_by"] != current_user.staff.email

    else
      @issue_response = EventResponse.new(json_data:, event_id: params[:issue_id],
                                          student_id: current_user.student.id)

      @issue.json_data["reopened_by"] = "" if @issue.json_data["reopened_by"] != current_user.student.username

    end
    @issue.json_data["update"] = !@issue.json_data["update"]
    @issue.update(json_data: @issue.json_data)

    @issue_response.save

    get_issues(@selected_project, @selected_order)

    return unless request.xhr?

    respond_to(&:js)
  end

  # Updates the issue's status to either open or resolved.
  # @return [JavaScript Response] A javascript response which rerenders the
  #   page with the issue moved to the corresponding section of with open
  #   issues or resolved issues. Also checks notification logic
  #   to see if notification icon needs to be removed.
  def update_status
    @issue = Event.find(params[:issue_id])

    @selected_project = params[:selected_project]
    @selected_order = params[:selected_order]

    if params[:status] == "closed"
      @issue.json_data["reopened_by"] = ""

      @issue.update(json_data: @issue.json_data, completed: true)
    else
      @issue.json_data["reopened_by"] = if current_user.is_staff?
        current_user.staff.email
      else
        current_user.student.username
      end

      @issue.update(json_data: @issue.json_data, completed: false)
    end

    get_issues(@selected_project, @selected_order)

    return unless request.xhr?

    respond_to(&:js)
  end

  private
    # Updates the instance variables @open_issues and @resolved_issues based
    #   on parameters from view to update the issues rendered in the view and
    #   their order.
    # @param [String] selected_project The current selected project in the view.
    # @param [String] selected_order The current selected order in the view.
    def get_issues(selected_project = "All", selected_order = "Created At")
      @open_issues = []
      @resolved_issues = []

      if current_user.is_admin?
        if selected_project != "All"
          project = CourseProject.find_by(name: selected_project)

          @project_groups = Group.where(course_project_id: project.id)
          group_ids = @project_groups.all.map(&:id).uniq
        else
          @user_projects = CourseProject.all
          group_ids = Group.all.map(&:id).uniq
        end

        if selected_order == "Created At"
          @open_issues = Event.joins(:group)
                              .where(groups: { id: group_ids })
                              .where(event_type: :issue)
                              .where(completed: false)
                              .order(created_at: :asc)

          @resolved_issues = Event.joins(:group)
                                  .where(groups: { id: group_ids })
                                  .where(event_type: :issue)
                                  .where(completed: true)
                                  .order(created_at: :asc)

        else
          @open_issues = Event.joins(:group)
                              .where(groups: { id: group_ids })
                              .where(event_type: :issue)
                              .where(completed: false)
                              .order(updated_at: :desc)

          @resolved_issues = Event.joins(:group)
                                  .where(groups: { id: group_ids })
                                  .where(event_type: :issue)
                                  .where(completed: true)
                                  .order(updated_at: :desc)
        end

      elsif current_user.is_staff?
        @user_modules = current_user.staff.course_modules

        @user_projects = []
        @user_modules.each do |user_module|
          @user_projects += user_module.course_projects
        end

        @project_groups = []
        @user_projects.each do |user_project|
          @project_groups += user_project.groups
        end

        if selected_project != "All"
          project = CourseProject.find_by(name: selected_project)

          @project_groups = Group.where(course_project_id: project.id)
        end

        group_ids = @project_groups.map(&:id).uniq
        if selected_order == "Created At"

          @open_issues = Event.joins(:group)
                              .where(groups: { id: group_ids })
                              .where(event_type: :issue)
                              .where(completed: false)
                              .order(created_at: :asc)

          @resolved_issues = Event.joins(:group)
                                  .where(groups: { id: group_ids })
                                  .where(event_type: :issue)
                                  .where(completed: true)
                                  .order(created_at: :asc)
        else

          @open_issues = Event.joins(:group)
                              .where(groups: { id: group_ids })
                              .where(event_type: :issue)
                              .where(completed: false)
                              .order(updated_at: :desc)
          @resolved_issues = Event.joins(:group)
                                  .where(groups: { id: group_ids })
                                  .where(event_type: :issue)
                                  .where(completed: true)
                                  .order(updated_at: :desc)
        end
      else
        @user_projects = current_user.student.course_projects
        @user_groups = current_user.student.groups
        group_ids = @user_groups.map(&:id).uniq

        if selected_project != "All"
          project = CourseProject.find_by(name: selected_project)

          group = current_user.student.groups.find_by(course_project_id: project.id)

          if !group.nil?
            group.id
            group_ids = [group.id].flatten
          else
            group_ids = []
          end
        end

        unless group_ids.empty?
          if selected_order == "Created At"
            @open_issues = Event.joins(:group)
                                .where(groups: { id: group_ids })
                                .where(event_type: :issue)
                                .where(completed: false)
                                .where(student_id: current_user.student.id)
                                .order(created_at: :asc)

            @resolved_issues = Event.joins(:group)
                                    .where(groups: { id: group_ids })
                                    .where(event_type: :issue)
                                    .where(completed: true)
                                    .where(student_id: current_user.student.id)
                                    .order(created_at: :asc)
          else
            @open_issues = Event.joins(:group)
                                .where(groups: { id: group_ids })
                                .where(event_type: :issue)
                                .where(completed: false)
                                .where(student_id: current_user.student.id)
                                .order(updated_at: :desc)

            @resolved_issues = Event.joins(:group)

app/views/issue/_issue-box.html.haml
-# This file is a part of Projman, a group project orchestrator and management system,
-# made by Team 5 for the COM3420 module [Software Hut] at the University of Sheffield.

.hidden-partial-container{ id: "hidden-partial-container-#{issue.id}"}
  - unique_id = "collapseIssue_#{issue.id}" # Generate a unique ID using SecureRandom
  - course_project = CourseProject.find_by(id: Group.find_by(id: issue.group.id).course_project_id)
  - course_module = CourseModule.find_by(id: course_project.course_module_id)
  - issue_responses = issue.event_responses

  .card.issue-card.mb-2.accordion-element{id: "issue-card-#{issue.id}"}
    %a.card-header.d-flex.justify-content-between.align-items-center{"data-bs-toggle" => "collapse",
      href: "##{unique_id}",
      role: "button",
      "data-accordion-toggle" => "",
      "aria-expanded" => "false",
      "aria-controls" => unique_id,
      id: "card-header-#{issue.id}"}
      .d-flex.align-items-center
        %span.me-3.fs-6.fw-light #{issue.created_at.strftime("%d/%m/%Y %H:%M")}
        %h3.m-0.fs-5.fw-medium #{issue.json_data['title']}
        %span
          // Adds notification icon if needed
          - if issue.notification?(current_user)
            %i.bi.bi-exclamation-diamond-fill.icon-pad
      %i.bi.bi-caret-right-fill
    .collapse{id: unique_id}
      .card-body.pt-1.pb-1
        // Renders the issue
        .d-flex.align-items-center.justify-content-between.pt-2.pb-2
          .fs-6 Posted by: #{issue.json_data['author']}
          .fs-6 #{course_module.code} - #{course_project.name}
        .fs-6 Issue:
        .issue-text.border.p-2.mb-2
          .fs-6 #{issue.json_data['content']}
        %hr.divider
        // Renders all the issue responses
        .container.issue-box-container{ id: "issue-box-container-#{issue.id}"}
          .row
            .scrollable{ id: "scrollable-#{issue.id}"}
              -issue_responses.each do |response|
                .d-flex.align-items-center.justify-content-between.pb-1
                  - if (current_user.is_staff? && response.staff_id == current_user.staff.id) || (current_user.is_student? && response.student_id == current_user.student.id)
                    .d-flex.w-100.justify-content-end
                      .w-75
                        .issue-text.border.p-2{ style: "background-color: lavender; border-radius: 10px;" }
                          .fs-6 #{response.json_data['content']}
                        .d-flex.align-items-center.justify-content-between.pb-2
                          .fw-light{ style: "font-size: 14px; padding-left: 6px;" } From: #{response.json_data['author']}
                          .fw-light{ style: "font-size: 14px; padding-right: 4px;" } #{DateTime.parse(response.json_data['timestamp']).strftime("%H:%M %d/%m/%Y")}
                  - else
                    .d-flex.w-100.justify-content-start
                      .w-75
                        .issue-text.border.p-2{ style: "background-color: #f0f0f0; border-radius: 10px;" }
                          .fs-6 #{response.json_data['content']}
                        .d-flex.align-items-center.justify-content-between.pb-2
                          .fw-light{ style: "font-size: 14px; padding-left: 6px;" } From: #{response.json_data['author']}
                          .fw-light{ style: "font-size: 14px; padding-right: 4px;" } #{DateTime.parse(response.json_data['timestamp']).strftime("%H:%M %d/%m/%Y")}
        - if !issue.completed
          %hr.divider
          // Form for sending a response to the issue
          = form_with(url: "/issues/issue-response", method: "post", local: false, id: "response-form-#{issue.id}") do |form|
            %input{ type: "hidden", name: "issue_id", value: "#{issue.id}"}
            %input{ type: "hidden", name: "author", value: "#{@current_user.givenname} #{@current_user.sn}"}
            %input{ type: "hidden", name: "selected_project", value: "#{@selected_project}"}
            %input{ type: "hidden", name: "selected_order", value: "#{@selected_order}"}
            .form_group
              = form.label :Response
              = form.text_area :response, class: "form-control pt-2 pb-2 mb-2", placeholder: "Enter your response here", id: "response-textarea-#{issue.id}", required: true
            .d-flex.justify-content-end.mb-2
              %button.btn.btn-primary{type: "submit", class: "btn btn-primary me-2", id: "send-response-#{issue.id}", remote: true }
                %i.bi.bi-send-fill
                Send
          - if current_user.is_staff?
            .d-flex.mb-2
              %button.btn.btn-primary{type: "button", "data-bs-toggle": "modal", "data-bs-target": "#resolveIssueModal-#{issue.id}", id: "mark-resolved-#{issue.id}"}
                Mark as resolved
        - if issue.completed
          .d-flex.justify-content-end.mb-2
            %button.btn.btn-primary{type: "button", "data-bs-toggle": "modal", "data-bs-target": "#reopenIssueModal-#{issue.id}", id: "reopen-#{issue.id}"}
              Reopen

    .modal.fade{id: "resolveIssueModal-#{issue.id}", tabindex: "-1", role: "dialog", aria: {labelledby: "resolveIssueModalLabel", hidden: "true"}}
      .modal-dialog.modal-dialog-centered
        .modal-content
          .modal-header
            %h5.modal-title{ id: "resolveIssueModalLabel" } Confirm Mark Issue as Resolved
            %button.btn-close{ "aria-label": "Close", "data-bs-dismiss": "modal", type: "button" }
          .modal-body
            Are you sure you want to mark this issue as resolved?
          .modal-footer
            %button.btn.btn-secondary{ type: "button", "data-bs-dismiss": "modal" } Cancel
            = form_with(url: update_status_issues_path(issue_id: issue.id, status: "closed"), method: :post, local: false, remote: true) do |form|
              %input{ type: "hidden", name: "selected_project", value: "#{@selected_project}"}
              %input{ type: "hidden", name: "selected_order", value: "#{@selected_order}"}
              = form.submit("Confirm", class: "btn btn-primary", "data-bs-dismiss": "modal")

    .modal.fade{id: "reopenIssueModal-#{issue.id}", tabindex: "-1", role: "dialog", aria: {labelledby: "reopenIssueModalLabel", hidden: "true"}}
      .modal-dialog.modal-dialog-centered
        .modal-content
          .modal-header
            %h5.modal-title{ id: "reopnIssueModalLabel" } Confirm Reopening Issue
            %button.btn-close{ "aria-label": "Close", "data-bs-dismiss": "modal", type: "button" }
          .modal-body
            Are you sure you want to reopen this issue?
          .modal-footer
            %button.btn.btn-secondary{ type: "button", "data-bs-dismiss": "modal" } Cancel
            = form_with(url: update_status_issues_path(issue_id: issue.id, status: "open"), method: :post, local: false, remote: true) do |form|
              %input{ type: "hidden", name: "selected_project", value: "#{@selected_project}"}
              %input{ type: "hidden", name: "selected_order", value: "#{@selected_order}"}
              = form.submit("Confirm", class: "btn btn-primary", "data-bs-dismiss": "modal")


:javascript
  $(document).ready(function() {
    $('#issue-card-#{issue.id}').on('shown.bs.collapse', '.collapse', function () {
      var issueBoxContainer = $('#issue-box-container-#{issue.id}');

      var elementToScrollTo = $('#hidden-partial-container-#{issue.id}');

      if (issueBoxContainer.length) {
        if (issueBoxContainer.get(0).scrollHeight > issueBoxContainer.innerHeight()) {
          issueBoxContainer.scrollTop(issueBoxContainer.get(0).scrollHeight);
        }
      };
    });
  });
  
-# elementToScrollTo.get(0).scrollIntoView();

app/views/issue/_issues-section.html.haml
-# This file is a part of Projman, a group project orchestrator and management system,
-# made by Team 5 for the COM3420 module [Software Hut] at the University of Sheffield.

.separating-section#open-issues-section
  %h2
    %i.bi.bi-chat-left-dots-fill.fill-yellow
    Open

  // Renders all open issues based on dropdown selections
  - if @open_issues.length > 0
    - @open_issues.each do |issue|
      - issue_url = issues_path() + "#issue-#{issue.id}"
      = render partial:'issue-box', locals: { issue: issue, issue_url: issue_url, selected_project: @selected_project, selected_order: @selected_order }
  - else
    .d-flex.justify-content-center
      %i.fs-6.fw-light You have no open issues
  %hr.divider

.separating-section#resolved-issues-section
  %h2
    %i.bi.bi-check-circle-fill.fill-green
    Resolved

  // Renders all resolved issues based on dropdown selections
  - if @resolved_issues.length > 0
    - @resolved_issues.each do |issue|
      - issue_url = issues_path(issue) + "#issue-#{issue.id}"
      = render partial:'issue-box', locals: { issue: issue, issue_url: issue_url, selected_project: @selected_project, selected_order: @selected_order }
  - else
    .d-flex.justify-content-center
      %i.fs-6.fw-light You have no resolved issues
  %hr.divider

app/views/issue/create.js.haml
-# This file is a part of Projman, a group project orchestrator and management system,
-# made by Team 5 for the COM3420 module [Software Hut] at the University of Sheffield.

:plain
  $('#reportIssueModal').modal('hide');

  document.getElementById('title').value = '';
  document.getElementById('description').value = '';

  $('#success-message').show();
  setTimeout(function() {
    $('#success-message').hide();
  }, 3000);

app/views/issue/issue_response.js.haml
-# This file is a part of Projman, a group project orchestrator and management system,
-# made by Team 5 for the COM3420 module [Software Hut] at the University of Sheffield.

:plain
  var currentIssue = $('#hidden-partial-container-#{params["issue_id"]}');
  var previousIssue = currentIssue.prev();
  currentIssue.remove();
  var newPartialHTML = "#{j(render(partial: 'issue-box', locals: { issue: Event.find(params["issue_id"]) }))}";
  $(previousIssue).after(newPartialHTML);

  var divider = $('#issues-section');
  var updatedPartialHTML = "#{j(render(partial: 'issues-section', locals: { issue: Event.find(params["issue_id"]) }))}";
  $(divider).html(updatedPartialHTML);

  if ("#{params[:selected_order]}" == "Created At") {
    var collapseElement = $('#issue-card-#{params["issue_id"]} .collapse');
    collapseElement.addClass('show');
    $('#card-header-#{params["issue_id"]}').attr('aria-expanded', 'true');
  } else {
    var collapseElement = $('#issue-card-#{params["issue_id"]} .collapse');
    collapseElement.addClass('show');
    $('#card-header-#{params["issue_id"]}').attr('aria-expanded', 'true');
    var elementToScrollTo = document.getElementById('hidden-partial-container-#{params["issue_id"]}');
    elementToScrollTo.scrollIntoView();
  }

  var issueBoxContainer = $('#issue-box-container-#{params["issue_id"]}');

  if (issueBoxContainer.length) {
    if (issueBoxContainer.get(0).scrollHeight > issueBoxContainer.innerHeight()) {
      issueBoxContainer.scrollTop(issueBoxContainer.get(0).scrollHeight);
    }
  };

  var openIssueSection = $('#open-issues-section');
  var resolvedIssueSection = $('#resolved-issues-section');
  var openToggleStatus = $('#flexSwitchCheckOpen').prop('checked');
  var resolvedToggleStatus = $('#flexSwitchCheckResolved').prop('checked');

  if (openToggleStatus) {
    openIssueSection.removeClass('display-none');
  } else {
      openIssueSection.addClass('display-none');
  }

  if (resolvedToggleStatus) {
    resolvedIssueSection.removeClass('display-none');
  } else {
      resolvedIssueSection.addClass('display-none');
  }

  var issuesBtn = $('#issues-btn');
  var notificationNeeded = #{current_user.issue_notification?};

  if (notificationNeeded) {
    issuesBtn.html('<a href="#{issues_url}" class="btn btn-light">Issues <i class="bi bi-exclamation-diamond-fill icon-pad-nav"></i></a>');
  } else {
    issuesBtn.html('<a href="#{issues_url}" class="btn btn-light">Issues</a>');
  };

app/views/issue/update_selection.js.haml
-# This file is a part of Projman, a group project orchestrator and management system,
-# made by Team 5 for the COM3420 module [Software Hut] at the University of Sheffield.

:plain
  var currentSelection = $("#dropdownMenuButton .current-selection");
  currentSelection.text("#{@selected_project}");

  var currentOrderSelection = $("#dropdownOrderMenuButton .current-selection");
  currentOrderSelection.text("#{@selected_order}");

  var divider = $('#issues-section');
  var updatedPartialHTML = "#{j(render(partial: 'issues-section', locals: { selected_project: @selected_project, selected_order: @selected_order }))}";
  $(divider).empty().append(updatedPartialHTML);
  $(divider).show();

  var openIssueSection = $('#open-issues-section');
  var resolvedIssueSection = $('#resolved-issues-section');
  var openToggleStatus = $('#flexSwitchCheckOpen').prop('checked');
  var resolvedToggleStatus = $('#flexSwitchCheckResolved').prop('checked');

  if (openToggleStatus) {
    openIssueSection.removeClass('display-none');
  } else {
      openIssueSection.addClass('display-none');
  }

  if (resolvedToggleStatus) {
    resolvedIssueSection.removeClass('display-none');
  } else {
      resolvedIssueSection.addClass('display-none');
  }

app/views/issue/update_status.js.haml
-# This file is a part of Projman, a group project orchestrator and management system,
-# made by Team 5 for the COM3420 module [Software Hut] at the University of Sheffield.

:plain
  var divider = $('#issues-section');
  var updatedPartialHTML = "#{j(render(partial: 'issues-section', locals: { issue: Event.find(params["issue_id"]) }))}";
  $(divider).html(updatedPartialHTML);

  if (#{params["status"]} == open) {
    var collapseElement = $('#issue-card-#{params["issue_id"]} .collapse');
    collapseElement.addClass('show');
    $('#card-header-#{params["issue_id"]}').attr('aria-expanded', 'true');
    var elementToScrollTo = document.getElementById('hidden-partial-container-#{params["issue_id"]}');
    elementToScrollTo.scrollIntoView();
  }

  $("#flexSwitchCheckOpen").prop("checked", true);
  $("#flexSwitchCheckResolved").prop("checked", true);

  var issuesBtn = $('#issues-btn')
  var notificationNeeded = #{current_user.issue_notification?}

  if (notificationNeeded) {
    issuesBtn.html('<a href="<%= j issues_url %>" class="btn btn-light">Issues <i class="bi bi-exclamation-diamond-fill icon-pad-nav"></i></a>');
  } else {
    issuesBtn.html('<a href="<%= j issues_url %>" class="btn btn-light">Issues</a>');
  }