config/routes.rb
# frozen_string_literal: true

# This file is a part of Projman, a group project orchestrator and management system,
# made by Team 5 for the COM3420 module [Software Hut] at the University of Sheffield.

Rails.application.routes.draw do
  devise_for :users

  mount EpiCas::Engine, at: "/"

  root "course_project#index"

  get "/profile", to: "page#profile"
  post "/profile/request-title-change", to: "page#request_title_change"
  
  get "/privacy", to: "page#privacy"
  get "/accessibility", to: "page#accessibility"

  get "/mail", to: "mailing#mail"
  post "/mail", to: "mailing#create"

  resources :projects, controller: :course_project do
    resource :milestone_responses, only: [:create], controller: :milestone_response

    post "/new", to: "course_project#create", on: :collection
    post "/edit", to: "course_project#update", on: :member
    post "/delete", to: "course_project#delete", on: :member

    # AJAX
    post "add_project_choice", on: :collection
    post "remove_project_choice", on: :collection
    post "add_project_milestone", on: :collection
    post "remove_project_milestone", on: :collection
    post "add_to_facilitator_selection", on: :collection
    post "remove_from_facilitator_selection", on: :collection
    post "add_facilitator_selection", on: :collection
    post "remove_facilitator", on: :collection
    post "clear_facilitator_selection", on: :collection
    post "toggle_project_choices", on: :collection
    get "search_facilitators", on: :collection
    get "get_milestone_data", on: :collection
    get "remove_milestone_email", on: :collection
    post "set_milestone_email_data", on: :collection
    post "set_milestone_comment", on: :collection
    get "search_facilitators_student", on: :collection
    get "search_facilitators_staff", on: :collection
    get "search_student_name", on: :collection

    post ":group_id/send-chat-message", to: "course_project#send_chat_message", on: :collection

    post "remake_teams", on: :member

    resources :teams, controller: :group do
      get "/teams", to: "group#index", on: :member
      post "facilitator_emails", on: :member
      post "set_facilitator", on: :member
      post "current_subproject", on: :member
      post "set_subproject", on: :member
      get "search_module_students", on: :collection
      post "add_student_to_team", on: :member
      post "remove_students_from_team", on: :member
    end

    resources :progress_form, controller: :progress_form do
      post "add_question" => "progress_form#add_question", on: :collection
      post "add_question" => "progress_form#add_question", on: :member
      post "delete_question" => "progress_form#delete_question", on: :collection
      post "delete_question" => "progress_form#delete_question", on: :member
      post "save_form" => "progress_form#save_form", on: :collection
      post "save_form" => "progress_form#save_form", on: :member
      post "delete_form" => "progress_form#delete_form", on: :collection
      post "delete_form" => "progress_form#delete_form", on: :member
      post "change_title" => "progress_form#change_title", on: :member
      post "change_title" => "progress_form#change_title", on: :collection

      post "show_new" => "progress_form#show_new", on: :collection
    end

    resources :mark_scheme, controller: :mark_scheme do
      post "add_section" => "mark_scheme#add_section", on: :collection
      post "add_section" => "mark_scheme#add_section", on: :member
      post "delete_section" => "mark_scheme#delete_section", on: :collection
      post "delete_section" => "mark_scheme#delete_section", on: :member
      post "save" => "mark_scheme#save", on: :collection
      post "save" => "mark_scheme#save", on: :member

      post 'add_to_assessors_selection' => 'mark_scheme#add_to_assessors_selection', on: :collection
      post 'add_assessors_selection' => 'mark_scheme#add_assessors_selection', on: :collection
      post 'clear_assessors_selection' => 'mark_scheme#clear_assessors_selection', on: :collection
      post 'remove_from_assessor_selection' => 'mark_scheme#remove_from_assessor_selection', on: :collection
      post 'remove_assessor_from_section' => 'mark_scheme#remove_assessor_from_section', on: :collection
      post 'get_assignable_teams' => 'mark_scheme#get_assignable_teams', on: :collection
      post 'assign_teams' => 'mark_scheme#assign_teams', on: :collection
      post 'auto_assign_teams' => 'mark_scheme#auto_assign_teams', on: :collection
      get 'search_assessors' => 'mark_scheme#search_assessors', on: :collection
      post "export_mark_scheme_with_results" => "mark_scheme#export_mark_scheme_with_results", on: :collection
      post "import_mark_scheme" => "mark_scheme#import_mark_scheme", on: :collection

      get 'marks' => 'mark_scheme#marks', on: :collection
      post 'show_new', on: :collection
    end
  end

  resources :students, only: [:index], controller: :student do
    post "/update_selection" => "student#update_selection", on: :collection
    get "/search_students" => "student#search_students", on: :collection
    post "/confirm_selection" => "student#confirm_selection", on: :collection
    post "/clear_selection" => "student#clear_selection", on: :collection
    post "/clear_student" => "student#clear_student", on: :collection
    post "/remove_students_from_module" => "student#remove_students_from_module", on: :collection
  end

  resources :issues, only: %i[index create], controller: :issue do
    # AJAX
    post "update-selection", to: "issue#update_selection", on: :collection
    post "issue-response", to: "issue#issue_response", on: :collection
    post "update-status", to: "issue#update_status", on: :collection
  end

  resources :facilitators, only: [:index], controller: :facilitator do
    get "teams/:team_id", to: "facilitator#team", as: "facilitator_team", on: :collection
    get "teams/:team_id/progress_form/:milestone_id", to: "facilitator#progress_form", as: "progress_form",
                                                      on: :collection

    # AJAX
    post 'update_teams_list' => 'facilitator#update_teams_list', on: :collection
    post 'update_progress_form_response' => 'facilitator#update_progress_form_response', on: :collection
  end

  resources :markings, controller: :marking do
    post 'save' => 'marking#save', on: :collection
  end

  resources :modules, controller: :course_module do
    post "/delete", to: "course_module#delete", on: :member
  end
end

app/models/course_module.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: course_modules
#
#  id         :bigint           not null, primary key
#  code       :citext           not null
#  name       :string(64)       not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  staff_id   :bigint
#
# Indexes
#
#  index_course_modules_on_code      (code) UNIQUE
#  index_course_modules_on_staff_id  (staff_id)
#
# Foreign Keys
#
#  fk_rails_...  (staff_id => staffs.id)
#

# This file is a part of Projman, a group project orchestrator and management system,
# made by Team 5 for the COM3420 module [Software Hut] at the University of Sheffield.

class CourseModule < ApplicationRecord
  has_and_belongs_to_many :students
  has_many :course_projects, dependent: :destroy
  belongs_to :staff

  validates :code, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/course_module_controller.rb
# frozen_string_literal: true

# This file is a part of Projman, a group project orchestrator and management system,
# made by Team 5 for the COM3420 module [Software Hut] at the University of Sheffield.

class CourseModuleController < ApplicationController
  authorize_resource

  before_action :set_module, only: %i[show edit update destroy]

  # GET /modules
  def index
    @admin_modules = if current_user.is_admin?
      CourseModule.all
    else
      CourseModule.where(staff_id: current_user.staff)
    end

    @show_create_button = current_user.is_admin?
  end

  # GET /modules/new
  def new
    @new_module = CourseModule.new
  end

  # POST /modules
  def create
    # Checks for unique module code
    unless CourseModule.where(code: (params[:course_module][:code]).strip).empty?
      redirect_to new_module_path, alert: "The Module Code is already in use."
      return
    end

    # Checks for correct e-mail confirmation
    @lead = params[:new_module_lead_email]

    @confirmation = params[:new_module_lead_email_confirmation]
    unless @lead == @confirmation
      redirect_to new_module_path, alert: "Unsuccesful - E-mail addresses did not match."
      return
    end

    # Creates new staff account if no staff found in system
    @lead = Staff.find_or_create_by(email: @lead)

    # Checks that the student_csv is compatible with the created module
    unless params[:student_csv].nil?
      @student_csv = CSV.read(params[:student_csv].tempfile)
      unless @student_csv[1][12] == params[:course_module][:code]
        redirect_to new_module_path,
                    alert: "The Student List Module {#{@student_csv[1][12]}} is not compatible with the Module Code {#{params[:course_module][:code]}}"
        return
      end
    end

    # Creates new module
    @new_module = CourseModule.new(code: params[:course_module][:code], name: params[:course_module][:name],
                                   staff_id: @lead.id)
    if @new_module.save
      Student.bootstrap_class_list(params[:student_csv].read) unless @student_csv.nil?
      redirect_to modules_path, notice: "Module was successfully created."
    else
      redirect_to new_module_path, alert: "Creation unsuccesful."
    end
  end

  # GET /modules/{id}
  def show
    @students = @current_module.students
    @module_lead = @current_module.staff
    @updated = @current_module.updated_at.strftime("%H:%M %d/%m/%Y")
    @created = @current_module.created_at.strftime("%H:%M %d/%m/%Y")

    @show_edit_buttons = current_user.is_admin?
  end

  # PATCH/PUT /modules/{id}
  def update
    @new_name = params[:new_module_name]
    @new_lead = params[:new_module_lead_email]
    @confirmation = params[:new_module_lead_email_confirmation]
    @new_student_list = params[:new_module_student_list]

    # Update Module Name modal
    unless @new_name.nil?
      @current_module.update_attribute(:name, @new_name)

      if @current_module.valid?
        redirect_to module_path, notice: "Module Name updated successfully."
      else
        redirect_to module_path, alert: "Update unsuccessful - Invalid name."
      end
    end

    # Update Module Lead modal
    unless @new_lead.nil?

      # Checks for correct e-mail confirmation
      unless @new_lead == @confirmation
        redirect_to module_path, alert: "Update unsuccesful - E-mail addresses did not match."
        return
      end

      # Creates new staff account if no staff found in system
      @new_lead = Staff.find_or_create_by(email: @new_lead)

      @current_module.update_attribute(:staff_id, @new_lead.id)

      if @current_module.valid?
        redirect_to module_path, notice: "Module Leader updated successfully."
      else
        redirect_to module_path, alert: "Update unsuccesful - Invalid e-mail."
      end
    end

    # Update Module Student List modal
    return if @new_student_list.nil?

    # Checks that the student_csv is compatible with the current module
    @parsed_csv = CSV.read(@new_student_list)
    unless @parsed_csv[1][12] == @current_module.code
      redirect_to module_path,
                  alert: "The Student List Module {#{@parsed_csv[1][12]}} is not compatible with the Module Code {#{@current_module.code}}"
      return
    end

    # Removes old student list and adds new one
    @current_module.students.clear
    Student.bootstrap_class_list(@new_student_list.read)
    redirect_to module_path, notice: "Student List updated successfully."
  end

  def delete
    course_module = CourseModule.find(params[:id])
    if course_module.destroy
      flash[:notice] = "Module successfully deleted"
      redirect_to modules_path
    else
      flash[:error] = "An error occurred"
    end
  end

  private
    def set_module
      @current_module = CourseModule.find(params[:id])
    end

    def module_params
      params.require(:course_module).permit(:code, :name, :staff_id, :student_csv)
    end
end

app/views/course_module/_student-list-box.html.haml
-# This file is a part of Projman, a group project orchestrator and management system,
-# made by Team 5 for the COM3420 module [Software Hut] at the University of Sheffield.

- unique_id = "student-list-card-#{SecureRandom.hex(5)}"  # Generate a unique ID
.card.list-card{id: unique_id}
  .card-header.d-flex.justify-content-between
    %h1
  .card-body.pt-1.pb-1
    %table.table
      %thead
        %tr
          %th{scope: "col"} Name
          %th{scope: "col"} Email
          %th{scope: "col"} UCard Number
        %tbody
          - @students.each do |student|
            %tr
              %td #{student.forename + ' ' + student.surname}
              %td #{student.email}
              %td #{student.ucard_number}

app/views/course_module/index.html.haml
-# This file is a part of Projman, a group project orchestrator and management system,
-# made by Team 5 for the COM3420 module [Software Hut] at the University of Sheffield.

-# Load all modules in the database

.separating-section
    .d-flex.align-items-center.justify-content-between
        %h2.fs-3
            Modules

        - if @show_create_button
            = link_to new_module_path, class: 'btn btn-primary' do
                %i.bi.bi-plus-square-fill
                Create New
    %hr.divider

    - @admin_modules.each do |mod|
        = link_to module_url(mod), class: "project-link" do
            .project-button
                %h3
                    #{mod.code + ' ' + mod.name}

- if @admin_modules.empty?
    .d-flex.justify-content-center
        %i.fs-6 You do not currently lead any modules, if you should be, please contact an admin.

app/views/course_module/new.html.haml
-# This file is a part of Projman, a group project orchestrator and management system,
-# made by Team 5 for the COM3420 module [Software Hut] at the University of Sheffield.

.separating-section
  %h2.fs-3
    Create Module

  %hr.divider

  = form_for @new_module, url: {action: "create"}, multipart: true, html: { id: 'new_module_form', method: :post } do |f|
    -# MODULE CODE
    .mb-3
      .input-group
        = f.label :code, "Module Code", class: "input-group-text fs-4 fw-semibold mb-0"
        = f.text_field :code, class: "form-control fs-5 fw-semibold", id: "course_module_code", placeholder: "Unique Code", required: true

    -# MODULE NAME
    .mb-3
      .input-group
        = f.label :name, "Module Name", class: "input-group-text fs-4 fw-semibold mb-0"
        = f.text_field :name, class: "form-control fs-5 fw-semibold", id: "course_module_name", placeholder: "Name", required: true

    -# MODULE LEADER
    .mb-3
      .input-group
        = f.label :staff_id, "Module Leader", class: "input-group-text fs-4 fw-semibold mb-0"
        %input.form-control.fs-5.fw-semibold{ type: "email", id: "new_module_lead_email", name: "new_module_lead_email",placeholder: "University of Sheffield E-mail", autocomplete: "off", required: true}
        %input.form-control.fs-5.fw-semibold{ type: "email", id: "new_module_lead_email_confirmation", name: "new_module_lead_email_confirmation",placeholder: "Confirm E-mail", autocomplete: "off", required: true}

    -# STUDENT CSV UPLOAD
    .mb-3
      %h1.fs-6.fw-normal.fst-italic= "[OPTIONAL]"
      .input-group
        = f.label :student_csv, "Module Student List (.csv)", class: "input-group-text fs-4 fw-semibold mb-0"
        %input.form-control.fs-5.fw-semibold{ type: "file", id: "student_csv", name: "student_csv",accept: "text/csv", autocomplete: "off"}
    %hr.divider

    -# SUBMIT
    %button.btn.btn-primary{ type: "submit", onclick: "showLoadingModal()" }= "Save"

= render partial: 'components/loading_modal'

app/views/course_module/show.html.haml
-# This file is a part of Projman, a group project orchestrator and management system,
-# made by Team 5 for the COM3420 module [Software Hut] at the University of Sheffield.

-# Show the currently selected module and all available options

:javascript
  // Function to expand the section to maxHeight
  function expandSection(button) {
    var section = button.closest('.list-card');
    var container = section.querySelector('.card-body');
    var content = container.querySelector('.table');
    var maxHeight = window.getComputedStyle(content).height.replace('px', '');
    var maxHeight = window.getComputedStyle(content).height;

    container.style.height = maxHeight;
  }

  // Function to shrink the height of the section to 200 pixels
  function shrinkSection(button) {
    var section = button.closest('.list-card');
    var container = section.querySelector('.card-body');
    container.style.height = '200px';
  }

  // This is to ensure that you cant expand the card more than the content of the table
  document.querySelectorAll('.list-card .card-body').forEach(function(container) {
    var content = container.querySelector('.table');

    var resizeObserver = new ResizeObserver(function(event) {
      var maxHeight = window.getComputedStyle(content).height.replace('px', '');
      var containerHeight = event[0].contentRect.height;

      resizeObserver.disconnect();

      if (containerHeight > maxHeight) {
        container.style.height = maxHeight + 'px';
      }

      requestAnimationFrame(function() { resizeObserver.observe(container); });
    });

    resizeObserver.observe(container);
  });

.separating-section
  .d-flex.align-items-center.justify-content-between
    .module-name
      %h2.fs-3 #{@current_module.code + ' ' + @current_module.name}

    = button_tag "Delete Module", type: "button", class: "btn btn-outline-danger", id: "delete-module-btn", style:"text-wrap: nowrap;", "data-bs-toggle": "modal", "data-bs-target": "#delete-module-modal"
  
  %hr.divider

  .d-flex.align-items-center.justify-content-between
    %h3 Module Name
    - if @show_edit_buttons
      %button.btn.btn-primary.btn-sm.m-2{type: "button", id: "change_name", "data-bs-toggle": "modal",
         "data-bs-target": "#changeNameModal"}
        Edit
  %i.fs-6 #{@current_module.name}
  %p

  %hr.divider

  .d-flex.align-items-center.justify-content-between
    %h3 Module Leader
    - if @show_edit_buttons
      %button.btn.btn-primary.btn-sm.m-2{type: "button", id: "change_lead", "data-bs-toggle": "modal",
         "data-bs-target": "#changeEmailModal"}
        Edit
  %i.fs-6 #{@module_lead.email}
  %p

  %hr.divider

  %h3 Updated / Created
  %i.fs-6 #{@updated} / #{@created}
  %p

  %hr.divider

  .d-flex.align-items-center.justify-content-between
    %h3 Student List
    - if @show_edit_buttons
      %button.btn.btn-primary.btn-sm.m-2{type: "button", id: "change_students", "data-bs-toggle": "modal",
         "data-bs-target": "#changeStudentListModal"}
        Edit
  =render partial: 'student-list-box', locals: {students: @students}

.modal.fade{ id: "changeNameModal", tabindex: "-1", "aria-labelledby": "changeNameModal", "aria-hidden": "true", "data-disallow-confirm-empty-input": "" }
  .modal-dialog.modal-dialog-centered.modal-dialog-scrollable
    .modal-content
      .modal-header
        %h1.modal-title.fs-5= "Change Module Name"
        %button.btn-close{ "aria-label": "Close", "data-bs-dismiss": "modal", type: "button" }

      .modal-body
        = form_tag module_path, method: :patch, id: 'name_form' do
          .form-group
            %input.form-control.fs-5.fw-semibold{ id: "new_module_name", name: "new_module_name", placeholder: "Name", autocomplete: "off", required: true }
            %h1
          .modal-footer
            %button.btn.btn-primary{ type: "submit", id: "name_confirm" }= "Confirm"

.modal.fade{ id: "changeEmailModal", tabindex: "-1", "aria-labelledby": "changeEmailModal", "aria-hidden": "true", "data-disallow-confirm-empty-input": "" }
  .modal-dialog.modal-dialog-centered.modal-dialog-scrollable
    .modal-content
      .modal-header
        %h1.modal-title.fs-5= "Change Module Leader"
        %button.btn-close{ "aria-label": "Close", "data-bs-dismiss": "modal", type: "button" }

      .modal-body
        = form_tag module_path, method: :patch, id: 'email_form' do
          .form-group
            %input.form-control.fs-5.fw-semibold{ type: "email", id: "new_module_lead_email", name: "new_module_lead_email",placeholder: "University of Sheffield E-mail", autocomplete: "off", required: true}
            %h1
            %input.form-control.fs-5.fw-semibold{ type: "email", id: "new_module_lead_email_confirmation", name: "new_module_lead_email_confirmation",placeholder: "Confirm E-mail", autocomplete: "off", required: true}
            %h1
          .modal-footer
            %button.btn.btn-primary{ type: "submit", id: "lead_confirm" }= "Confirm"

.modal.fade{ id: "changeStudentListModal", tabindex: "-1", "aria-labelledby": "changeStudentListModal", "aria-hidden": "true", "data-disallow-confirm-empty-input": "" }
  .modal-dialog.modal-dialog-centered.modal-dialog-scrollable
    .modal-content
      .modal-header
        %h1.modal-title.fs-5= "Change Module Student List"
        %button.btn-close{ "aria-label": "Close", "data-bs-dismiss": "modal", type: "button" }

      .modal-body
        %h1.fs-6.fw-normal.fst-italic= "This will clear the current student list and replace it with new students."
        %h1.fs-6.fw-normal.fst-italic= "* This could take up to 2 minutes."
        = form_tag module_path,  method: :patch, multipart: true, id: 'student_form' do
          .form-group
            %input.form-control.fs-5.fw-semibold{ type: "file", id: "new_module_student_list", name: "new_module_student_list", autocomplete: "off", accept: "text/csv", required: true}
            %h1
          .modal-footer
            %button.btn.btn-primary{ type: "submit", id: "list_confirm", "data-bs-dismiss": "modal", onclick: "showLoadingModal()" }= "Confirm"

.modal.fade{ id: "delete-module-modal", tabindex: "-1", "aria-labelledby": "delete-module-modal", "aria-hidden": "true" }
  .modal-dialog.modal-dialog-centered.modal-dialog-scrollable
    .modal-content
      .modal-header
        %h1.modal-title.fs-5 Delete Module
        %button.btn-close{ "aria-label": "Close", "data-bs-dismiss": "modal", type: "button" }

      .modal-body
        %p Are you sure you want to delete this module? You cannot undo this action

      .modal-footer.d-flex.justify-content-end
        %button.btn.btn-secondary{ type: "button", "data-bs-dismiss": "modal" } Close
        = form_tag(delete_module_path, method: "post") do
          = button_tag "Yes, Delete It", type: "submit", class: "btn btn-danger"

= render partial: 'components/loading_modal'